### ISSUE TITLE
Do not provide a logging implementation, only an API

### ISSUE THREAD

**Issue by EricRademacher** [dcm4che/dcm4che#1045]
**Describe the bug**
The dcm4che-* modules come with a dependency to org.slf4j:slf4j-log4j12 additionally to the API org.slf4j:slf4j-api. This is in conflict with any logging implementation/framework an application might be using instead.
As a library, dcm4che should provide only the API to the logging framework, not any implementation.

**Expected behavior**
As a dependency only a logging API, no org.slf4j:slf4j-log4j12. For this API an application which uses dcm4che can provide its own implementation.

**Comment by gunterze** [comment]
There is no dependency on `org.slf4j:slf4j-log4j12` by dcm4che library modules!
```
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
        <version>${slf4j.version}</version>
        <scope>runtime</scope>
      </dependency>
```
only reflects the dependency for including slf4j-log4j12 and log4j into the binary distribution package for use by utility launchers, which make use of them. But you may also use another slf4j provider running the utilities by adjusting the classpath in the launcher scripts.

**Comment by EricRademacher** [comment]
Thanks for the quick reply!
While you provided the extract from the `<dependencyManagement>` section of the parent POM, the modules like `dcm4che-core` nonetheless have a direct runtime dependency to `org.slf4j:slf4j-log4j12`:
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
</dependency>
```

The effect for our application using the module `dcm4che-core` as-is is that when building our application we have `log4j:log4j` included in our application additionally to the logging framework we are using. This has two disadvantages for us:
1. Two logging frameworks instead of one (dcm4che's `log4j:log4j` and the one we are using).
2. `log4j:log4j:1.2.17` comes with several security issues found by our software analysis tool.

Of course we could simply exclude `org.slf4j:slf4j-log4j12` in our pom.xml; however, in our opinion a library should not come with any logging framework and the using application provides their own one. That is why I wrote this ticket.
If the `dcm4che-tool-*` modules still need this logging bridge, it would be best to move the runtime dependency exclusively to the module `dcm4che-tool` while the library modules like `dcm4che-core` only have a dependency to `org.slf4j:slf4j-api`. Do you agree?

**Comment by gunterze** [comment]
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
</dependency>
```
in `dcm4che-core` is not intended - will remove it - but also has no affect to the built library, which does not get dependent just because maven includes it in its classpath during the build.
