### ISSUE TITLE
Update jaxb runtime version to 4.0.1

### ISSUE THREAD

**Issue by FranzWiller** [dcm4che/dcm4che#1153]
**Is your feature request related to a problem? Please describe.**

Version 2.3x is rather old and not fully compatible to current version used in other product / environment.

**Describe the solution you'd like**
Update jaxb-runtime.version to 4.0.1 and depending dependencies (jakarta.xml.bind.version, jakarta.activation.version,..) .

**Describe alternatives you've considered**

**Additional context**

**Comment by gunterze** [comment]
[Wildfly 26.1.0.Beta1](https://mvnrepository.com/artifact/org.wildfly.bom/wildfly-jakartaee8/26.1.0.Beta1) still relies on 

Group / Artifact | Version
-- | -- 
org.jboss.spec.javax.xml.ws » jboss-jaxws-api_2.3_spec | 2.0.0.Final
org.glassfish.jaxb » jaxb-runtime | 2.3.3-b02
org.glassfish.jaxb » txw2 | 2.3.3-b02

so upgrading to 3.0.2 would risk usage of jaxb generated classes of module dcm4che-audit in dcm4chee-arc.

Will upgrade, as soon Wildfly does.
