### ISSUE TITLE
dcm2dcm tool: Transcode to jpeg (lossy) not working

### ISSUE THREAD

**Issue by Strealox** [dcm4che/dcm4che#1159]
Hi, I'm trying to transcode a dicom (TSUID: 1.2.840.10008.1.2.1) to a dicom with a lossy jpeg  (TSUID: 1.2.840.10008.1.2.4.50 or .51) with command 'dcm2dcm --jpeg img.dcm jpeg.dcm'. But the resulting dicom has TSUID 1.2.840.10008.1.2.4.70.

**Comment by gunterze** [comment]
Caused by 83bb2072e64ac50d7edd13ed40bd2b5a7295d5b3 as part of https://github.com/dcm4che/dcm4che/pull/825

Fixed for
- _Bits Stored (0028,0101)_ <= 12 and 
- _PixelRepresentation (0028,0103)_ = 0 (=unsigned Pixeldata)
