### ISSUE TITLE
DCM4CHEE dont start after stop service

### ISSUE THREAD

**Issue by alexandremcp** [dcm4che/dcm4che#1166]
I have DCM4CHEE installed on a local server.

The server's HD was full and I had to, emergency, delete old files.

After restarting the system giving stop and soon after start, the system did not respond again.

The Oviyam screen loads, however, when trying to search for images to view the system gives an error and does not load the images.
What can I do to resolve this issue?

Thanks

**Comment by insinfo** [comment]
I don't know the dcm4che/Oviyam system very well, but from what I've seen, I think Oviyam 2.7.1 is not paging on the server side, it seems that it downloads all the records from the database to the browser which causes a memory overflow, does @vrindaayak have any solution for this?

![image](https://user-images.githubusercontent.com/12227024/163860874-5ce0786f-8f2d-495e-8912-36a2d18cba0d.png)
![WhatsApp Image 2022-04-18 at 15 59 33](https://user-images.githubusercontent.com/12227024/163860897-48ea3d9e-881e-42ce-af15-c6221e4d5829.jpeg)

![image](https://user-images.githubusercontent.com/12227024/163861441-12537b50-2231-471a-8d4c-a3c358f071bf.png)

**Comment by vrindanayak** [comment]
@alexandremcp / @insinfo : Oviyam viewer software is not developed / maintained by us. Please contact the Oviyam developers on [dcm4che user forum](uploadedFiles/Documents/Radiology/IHE_RAD_Suppl_IOCM.pdf)

**Comment by insinfo** [comment]
@vrindanayak 
sorry for opening the issue in the wrong place, what is the official repository of Oviyam ? The link you posted is broken.
![image](https://user-images.githubusercontent.com/12227024/164035003-831fd225-27f9-4505-b5a6-210703e030f8.png)

**Comment by vrindanayak** [comment]
@insinfo : Sorry for the wrong link. Dcm4che user forum - https://groups.google.com/g/dcm4che
