### ISSUE TITLE
File access collision when receiving same dicom file simultaneously in StoreSCP

### ISSUE THREAD

**Issue by fmarot** [dcm4che/dcm4che#1189]
**Describe the bug**

When the same dicom file is received in parallel, the multiple threads handling it try to access and write the same destination file simultaneously, hence error happen.

**To Reproduce**
This simple class outputs many errors in the logs

```
 import java.io.File;

 import org.dcm4che3.tool.storescp.StoreSCP;
 import org.dcm4che3.tool.storescu.StoreSCU;

 import lombok.extern.slf4j.Slf4j;

 /** This class is for testing *manually* the SCP Server */
 public class ManualTester2 {

	public static void main(String[] args) throws Exception {

		int serverPort = 11_112;
		String[] scpArgs = new String[] { "-b",
				"aaa@127.0.0.1:11112",
				"--accept-unknown" };
		StoreSCP.main(scpArgs);

		for (int i = 0; i < 10; i++) {
			Thread t = new Thread(() -> {
				File dcmFilesToSendDir = new File("/path/to/your/single/file.dcm");
				String[] scuArgs = new String[] { "-c", "aaa@127.0.0.1:" + serverPort, dcmFilesToSendDir.toString() };
				StoreSCU.main(scuArgs);
			});
			t.start();
		}

		Thread.sleep(10000);
	}
}
```

**Expected behavior**
No errors should be shown, each file sent should overwrite the previous one silently if they are the same.

**Desktop (please complete the following information):**
The behavior was observed on Windows and Linux with dcm4che 5.25.2 and 5.24.2

**Additional context**
I'm not sure how often simultaneously receiving the same file happens in the real world but I face this problem at a partner's site, hence, I'm inclined to think it happens sometimes.

Additionally, I feel like the previous attempts to resolve this issue ( https://github.com/dcm4che/dcm4che/issues/1112 ) was not entirely sufficient: `File.createTempFile(iuid, PART_EXT, storageDir);` was enough to prevent collisions on the temporary file, but collisions still happen on renaming the temp file to the final file

**Workaround**

The workaround I propose (and will propose as a PR) is to just add the `synchronized` keyword to the "renameTo" method.
Hence

``` private static void renameTo(Association as, File from, File dest)```

would become

``` private synchronized static void renameTo(Association as, File from, File dest)```

I tested this fix and it does the job.
An alternative (maybe faster) would be to keep in a List the last 100 or so filenames and lock only on the filenames so that we would do lock for every file but only for real collisions, but I feel like it would be a lot more complex both to explain and maintain. And performance gain would have to be proven.

**Comment by or150** [comment]
Hi,

Copying here the same comment I replied in my original [issue](https://github.com/dcm4che/dcm4che/issues/1103) ([discussion](https://github.com/dcm4che/dcm4che/discussions/1108), [PR](https://github.com/dcm4che/dcm4che/pull/1104)):


> Hi,
> 
> My suggested fix included a second part, with retries on the rename.
> The reasons I went with retries instead of locks were:
> 
> It doesn't affect performance as much as locks
> It allows running two listeners that write to the same directory.
> I did performance tests on a very high velocity throughput that represents one of our use cases and was able to reduce the issue to a practically nonexistent level with 3 retries.

**Comment by fmarot** [comment]
Thanks @or150 . I had missed this part of your proposal when reading the mentioned discussion. I think @gunterze also missed the collision in renameTo as it is still an issue. There are 2 fix proposals now, please pick one ! ;)

I admit I prefer mine as it is much more simple. But it may be a bit behind performance-wise, not sure.

**Comment by gunterze** [comment]
Chose @or150 's solution, adding options
```
    --rename-retries <count>         The amount of retries to perform if
                                     M-RENAME stage fails. 3 retries by
                                     default.
    --rename-retry-jitter <ms>       The maximal random jitter inserted
                                     between M-RENAME retires. 50ms by
```
