### ISSUE TITLE
Cannot specify localport in "dcm4che-tool-getscu" 

### ISSUE THREAD

**Issue by Honeytree-svg** [dcm4che/dcm4che#1192]
**Describe the bug**
when use GetSCU to connect remote AE, the local port always 0.

**To Reproduce**
1. Use something like following command line: getscu -b GETSCU@192.168.221.4:11111 -c DCMQRSCP@192.168.1.9:3333 -m StudyInstanceUID=1.2.3.4 --directory /usr/home/dicom

2. see log: INFO org.dcm4che3.net.Connection - Initiate connection from /192.168.221.4:0 to 192.168.1.9:3333

**Additional context**
Maybe, i have found the key of this problem. 
the code at org.dcm4che3.net.Connection  line 772

**Comment by gunterze** [comment]
getscu is not listening for incoming association requests, so the specified port number in the value of option
```
 -b,--bind <aet[@ip][:port]>              specify AE Title, local address
                                          of the Application Entity
                                          provided by this application;
                                          use GETSCU and pick up any valid
                                          local address to bind the socket
                                          by default. If also a port is
                                          specified, the Application
                                          Entity will listening for
                                          incoming association requests on
                                          it.
```
is not effective. Will adjust the help text accordingly.
