### ISSUE TITLE
hi,the dcm2jpg method why not provide the option to get all jpgs  

### ISSUE THREAD

**Issue by qinghuozhang** [dcm4che/dcm4che#1227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gunterze** [comment]
Please ask questions at [GitHub dcm4che Discussions](https://github.com/dcm4che/dcm4che/discussions) or [dcm4che - Google Group](https://groups.google.com/g/dcm4che).
