### ISSUE TITLE
Attributes.toString() does not list attributes ordered by increasing Data Element Tag 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#1279]
`Attributes.toString()` does not list attributes ordered by increasing Data Element Tag . Particularly, attributes with Data Element Tag > _(7FFF,FFFF)_ are listed before attributes with Data Element Tag <= _(7FFF,FFFF)_ .

**Comment by hczedik** [comment]
Just a suggestion: It would be good to cover this with unit tests, including the special case now fixed with d62f150cbbe1fa6c98b780af3b0caabe6c0b0767.
