### ISSUE TITLE
Command Line Attributes Not Parsed Correctly by Command Line Tools in Windows

### ISSUE THREAD

**Issue by jasondalycan** [dcm4che/dcm4che#1280]
When using the command line tools, settings parameter attributes is ok in Linux but in Windows the attributes are dropped.  See the following example:

```
In Linux (bash):

# This works
storescu -c myaet@localhost:4242 -s PatientName=Mike myfile.dcm
```

```
In Windows (PowerShell or CMD):

# This does not work
storescu -c myaet@localhost:4242 -s PatientName=Mike myfile.dcm
```

In Windows the following error is received:

<pre>
java.lang.IllegalArgumentException: Mike
        at org.dcm4che3.tool.common.CLIUtils.toTag(CLIUtils.java:686)
        at org.dcm4che3.tool.common.CLIUtils.toTags(CLIUtils.java:676)
        at org.dcm4che3.tool.common.CLIUtils.addAttributes(CLIUtils.java:804)
</pre>

It appears that since the command line tools are batch files the '=' between the parameter key and value is dropped thus causing the issue.

**Comment by gunterze** [comment]
Guess you need to quote the arguments containing `=`

**Comment by jasondalycan** [comment]
I tried the following quoting approached and none worked:

`storescu -c myaet@localhost:4242 -s 'PatientName=Mike' myfile.dcm
`
`storescu -c myaet@localhost:4242 -s "PatientName=Mike" myfile.dcm
`
`storescu -c myaet@localhost:4242 '-sPatientName=Mike' myfile.dcm
`

They all thrown the same exception:

<pre>
java.lang.IllegalArgumentException: Mike
        at org.dcm4che3.tool.common.CLIUtils.toTag(CLIUtils.java:686)
        at org.dcm4che3.tool.common.CLIUtils.toTags(CLIUtils.java:676)
        at org.dcm4che3.tool.common.CLIUtils.addAttributes(CLIUtils.java:804)
</pre>

**Comment by gunterze** [comment]
You have to separate the options which support multiple values from the program  arguments by `--`.

```
storescu -c myaet@localhost:4242 -s 'PatientName=Mike' -- myfile.dcm
```

**Comment by jasondalycan** [comment]
Ok that works thanks
