### ISSUE TITLE
Wrong VR for SourceApplicationEntityTitle in Attributes created by Association.createFileMetaInformation(..)

### ISSUE THREAD

**Issue by jib63** [dcm4che/dcm4che#130]
On the master ( and on the other branches ), on line 1228 of Association.java in createFileMetatInformation ( project dcm4che-net ) we can find :
  fmi.setString(Tag.SourceApplicationEntityTitle, VR.SH, getRemoteAET());

The VR use shall be AE and not SH see the following link
https://www.dabsoft.ch/dicom/6/7/#(0002,0016)

This shall be changed to 
  fmi.setString(Tag.SourceApplicationEntityTitle, VR.AE, getRemoteAET());

**Comment by hczedik** [comment]
@gunterze is this a typo or was it done on purpose?

**Comment by jib63** [comment]
I told Gunter about this issue at last Connectathon in Venice. I agreed that it was a bad copy/pasting

**Comment by gunterze** [comment]
Sorry, forgot to fix it. Thanks, for remembering.
