### ISSUE TITLE
BasicCStoreSCU returns only first failing SOPInstanceUID

### ISSUE THREAD

**Issue by jensstockhausen** [dcm4che/dcm4che#136]
The function  private BasicCStoreSCUResp makeRSP(int status) collects the UIDs of the instances that failed to be transferred. 

But the returned response contains only the first UID.
```Java
if (!failed.isEmpty()) {
            String[] iuids = new String[failed.size()];
            for (int i = 0; i < iuids.length; i++)
                iuids[i] = failed.get(0).iuid;
            rsp.setFailedUIDs(iuids);
}
```

the failed.get(0).iuid; ought to be replaced by a failed.get(i).iuid;

**Comment by hczedik** [comment]
Thanks a lot @jensstockhausen for finding this!
