### ISSUE TITLE
Decompression of J2K YBR_RCT/YBR_ICT results in wrong RGB colors

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#1374]
Decompression of J2K YBR_RCT/YBR_ICT results in wrong RGB colors

E.g. decompression of `IMAGES/J2KR/US1_J2KR` from `ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04/compsamples_j2k.tar` results in

```
00000570  30 30 e0 7f 10 00 4f 57  00 00 00 10 0e 00 00 7d  |00....OW.......}|
00000580  00 00 7d 00 00 7d 00 00  7d 00 00 7d 00 00 7d 00  |..}..}..}..}..}.|
00000590  00 7d 00 00 7d 00 00 7d  00 00 7d 00 00 7d 00 00  |.}..}..}..}..}..|
000005a0  7d 00 00 7d 00 00 7d 00  00 7d 00 00 7d 00 00 7d  |}..}..}..}..}..}|
```
instead of
```
00000570  30 30 e0 7f 10 00 4f 57  00 00 00 10 0e 00 00 00  |00....OW........|
00000580  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000590  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000005a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```
rendered to
![US1_J2KR](https://github.com/dcm4che/dcm4che/assets/400095/3ba9dddb-b51e-4781-ba0d-f13705dd3236)
instead to
![US1_J2KR](https://github.com/dcm4che/dcm4che/assets/400095/a177a024-8458-47be-8ebc-5a7e6a6f093b)

Introduced by #1365 (reverted native codecs to 4.8.0 for now)

**Comment by hczedik** [comment]
Just a suggestion: Would be good to cover this with automated tests to avoid such regressions in the future. (If it isn't already.)

**Comment by nroduit** [comment]
I don't have this problem in my tests, which also use version 4.8.1. I'll have to take a closer look because dcm4che has a different color model management.

**Comment by nroduit** [comment]
In fact, the jpeg2000 decoder now also uses an implementation to [force the use of YBR_FULL](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio-opencv/src/main/java/org/dcm4che3/opencv/NativeImageReader.java#L295) in the native decoders. The version 4.8.1 correctly decodes this example [ybrFull_j2k-no-jp2-header.dcm.zip](https://github.com/dcm4che/dcm4che/files/13463538/ybrFull_j2k-no-jp2-header.dcm.zip) (jpeg2000 without jp2 metadata and YBR_FULL from DICOM), which is [allowed by the standard](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.4.html). dcm4che versions prior to 5.31.2 do not decode it correctly.
 
However, in the case of YBR_ICT and YBR_RCT, YBR mode should not be forced (excluded in my commit and it also [matches with the new implementation of the decoders](https://github.com/nroduit/weasis-dicom-tools/blob/master/src/main/java/org/dcm4che3/img/DicomImageReader.java#L324-L325)), as these are the modes used by default.

**Comment by nroduit** [comment]
Note that [the OpenCV wrapper project](https://github.com/nroduit/weasis-core-img) now has full coverage for unit testing, and all classes providing APIs have [documentation on each method](https://github.com/nroduit/weasis-core-img/blob/master/src/main/java/org/weasis/opencv/op/ImageProcessor.java).
