### ISSUE TITLE
High system load if many syslog messages are queued in spool directory

### ISSUE THREAD

**Issue by markusgr** [dcm4che/dcm4che#143]
We are using dcm4che-net-audit version 3.3.7 on Wildfly 10. If more than several hundreds messages are queued in the spool directory because the messages couldn't be send, the system load increases significantly. In our case from about 5% up to >70%.
We identified that this is caused by sorting the files by last modified date in class org.dcm4che3.net.audit.AuditLogger.
Solution can be either to cache the sorted file list or by disable the sorting because I don't think that it is necessary to send the messages ordered by time.

**Comment by gunterze** [comment]
Cache last modified time of files before sorting to avoid repeated system calls during sort.
