### ISSUE TITLE
https://www.dcm4che.org/maven2 down?

### ISSUE THREAD

**Issue by ebremer** [dcm4che/dcm4che#1440]
I cannot access
https://www.dcm4che.org/maven2
nor
https://www.dcm4che.org

**Comment by gunterze** [comment]
Not for me:
´´´
$ curl https://www.dcm4che.org/maven2
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.25.5</center>
</body>
</html>
```

**Comment by ebremer** [comment]
It did work when I tried from my University's network.  Perhaps my ISP (Optimum.net) is blocking it?  I will do some more checks.

**Comment by ebremer** [comment]
I found the problem.  It was #975.  I never took the DNS fix entry out of my local configuration.  When I was able to access the web site from a different computer on my local network, I realized it had to be computer-specific.  Did the web site change ip addresses recently?  My #975 mod has been in there for years.  I'm not sure why it started acting up now, but it's fixed now.
