### ISSUE TITLE
org.dcm4che3.data.Tag  Not Found

### ISSUE THREAD

**Issue by huan920924** [dcm4che/dcm4che#157]
When I use dcm4che, I can not find some files
` import org.dcm4che3.data.Tag;
import org.dcm4che3.data.UID;`
can you help me？

**Comment by hczedik** [comment]
Please use the [dcm4che Google user group](https://groups.google.com/forum/#!forum/dcm4che) for questions. Thanks.

**Comment by grossshen** [comment]
these answers under https://groups.google.com/forum/#!forum/dcm4che   works. But i still can't figure out why Tag class and UID class can't be found in Source Files? but i can find the Tag.class and UID.class after mvn compile. This problem makes me confused.

**Comment by hczedik** [comment]
These classes get generated during the Maven build.

**Comment by grossshen** [comment]
Sorry. I have't describe my problem correctly. What confuses me is why the author don't add these classes in source files but generate them during the Maven build(It's a project design problem).  Thank you for you help ,hczedik.
