### ISSUE TITLE
Is the the capability to read the Patient ID, name, dob from a DICOMDIR and then update it if needed?

### ISSUE THREAD

**Issue by L3dge** [dcm4che/dcm4che#167]
Hi

I have been searching through the doco and cannot find if there is the ability to read the patient data from a DICOMDIR file.  I need to lookup other systems to see if the patient exists and then update the DICOMDIR file with a new patient ID before sending it to a PACS.

Any help would be appreciated.

**Comment by hczedik** [comment]
Please use the Google Group for questions
https://groups.google.com/d/forum/dcm4che
