### ISSUE TITLE
API changes report for Dcm4che Net

### ISSUE THREAD

**Issue by lvc** [dcm4che/dcm4che#172]
The review of API changes for the Dcm4che Net library since 3.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/dcm4che-net/

Hope it will be helpful for users and maintainers of the library. The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://www.dcm4che.org/maven2/org/dcm4che/dcm4che-net/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![dcm4che-net-2](https://user-images.githubusercontent.com/1517837/31112707-f45ef6a2-a81d-11e7-8a45-17dec8ffa7e5.png)
![dcm4che-net-1](https://user-images.githubusercontent.com/1517837/31112706-f44997e4-a81d-11e7-81ab-76ffb03fcfe1.png)

**Comment by hczedik** [comment]
Thank you Andrey for the information! Excellent tool you have created here!

**Comment by hczedik** [comment]
@gunterze I think it would make sense to always apply this tool for the whole library before releases, to get an overview how backwards compatible the changes are.

**Comment by lvc** [comment]
The profile used to generate reports: https://github.com/lvc/upstream-tracker-4j/blob/master/profile/dcm4che-net.json

Commands to plot/update the report daily:

    japi-monitor profile/dcm4che-net.json -get -build-new
    japi-tracker profile/dcm4che-net.json -build
    japi-tracker profile/dcm4che-net.json -build -t graph -rss

To check for API changes before the release just make a beta or alpha version and it will appear at the top of the compatibility table.

Thank you.
