### ISSUE TITLE
Building fails with Java 9

### ISSUE THREAD

**Issue by ghost** [dcm4che/dcm4che#177]
Trying to follow the docs, but building fails.

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dcm4che-audit: Compilation failure: Compilation failure:
[ERROR] /dicom/dcm4che/dcm4che-audit/src/main/java/org/dcm4che3/audit/AuditMessages.java:[676,19] cannot find symbol

...(lots of such errors)...

Moreover, the docs for dcm4chee-arc-light says I should clone dcm4che and checkout a non-existing dcm4chee-arc-light branch.

Duplicate #335

**Comment by hczedik** [comment]
The build works, see https://travis-ci.org/dcm4che/dcm4che/

I've correct the branch name in the archive README, see https://github.com/dcm4che/dcm4chee-arc-light/pull/1037

**Comment by notsonotso** [comment]
@hczedik nope, the build still fails on macOS at least. Following the new build instructions.

**Comment by hczedik** [comment]
Hi,
which version of Java are you using? Which version of Maven?

**Comment by notsonotso** [comment]
@hczedik Java 9, mvn 3.3.9

**Comment by Toenex** [comment]
I get the same build failure on both MacOS High Sierra and Ubuntu 17.10 when using Java 9.  I've tested Ubuntu 17.10 with Java 8 and it builds without issue.  I'm not able to test MacOS with Java 8 but suspect the issue relates to Java 9.

`git clone https://github.com/dcm4che/dcm4che.git`
`cd dcm4che`
`mvn install`

> [mvn_install_short.txt](https://github.com/dcm4che/dcm4che/files/1443993/mvn_install_short.txt)

`mvn -version`

> Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T08:58:13+01:00)
> Maven home: /usr/local/Cellar/maven/3.5.2/libexec
> Java version: 9.0.1, vendor: Oracle Corporation
> Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
> Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"

**Comment by Hesham-Elbadawi** [comment]
Hi,

This has nothing to do with the java version.
The entities in the audit package are generated with maven jaxb2 plugin and have to be added to the class path upon generation so the rest of ur code can be interpreted.

These include ActiveParticipant, etc...

I believe the goal xjc which generates the pojos from the xml binding is not triggered by default with maven jaxb2 version 1.5 on java9 so maybe try to upgrade it to a higher version or run the plugin first in the audit package folder prior to running mvn install.

Good luck,
Hesham

**Comment by Toenex** [comment]
Hi,

Executing the xjc goal explicitly in `dcm4che-audit` didn't work.

`cd dcm4che`
`mvn clean`
`cd dcm4che-audit`
`mvn org.codehaus.mojo:jaxb2-maven-plugin:xjc` 
> succesful : [mvn.txt](https://github.com/dcm4che/dcm4che/files/1444385/mvn.txt)

`cd ..`
`mvn install`
> failed (same as before) : [mvn.txt](https://github.com/dcm4che/dcm4che/files/1444392/mvn.txt)

Also changing the version of `jaxb2-maven-plugin` to anything over 1.5 (1.6 & 2.3) gives the following errors [mvn.txt](https://github.com/dcm4che/dcm4che/files/1444401/mvn.txt).

**Comment by Hesham-Elbadawi** [comment]
Hi,
As mentioned before They are only generated but not added to classpath.

According to the plugin site issue https://github.com/mojohaus/jaxb2-maven-plugin/issues/43 it does fail with java 9 for the previously mentioned phase not being executed correctly.

Although there is a way to work around it using the antrun, exec and buildhelper plugins to invoke the jaxb plugin explicitly and adding it to classpath.

Try this recipe after changing the paths for the files in it according to dcm4che audit files appropriately.
 <plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-antrun-plugin</artifactId> <version>1.4</version> <executions> <execution> <phase>generate-sources</phase> <configuration> <tasks> <echo message="Creating target/generated-sources/jaxb"/> <mkdir dir="./target/generated-sources/jaxb"/> </tasks> </configuration> <goals> <goal>run</goal> </goals> </execution> </executions> </plugin>  <plugin> <groupId>org.codehaus.mojo</groupId> <artifactId>exec-maven-plugin</artifactId> <executions> <execution> <id>generate schema types</id> <phase>generate-sources</phase> <goals> <goal>exec</goal> </goals> </execution> </executions> <configuration> <executable>xjc</executable> <arguments> <argument>-enableIntrospection</argument> <argument>-p</argument> <argument>org.hibernate.validator.internal.xml</argument> <argument>-extension</argument> <argument>-target</argument> <argument>2.1</argument> <argument>-d</argument> <argument>target/generated-sources/jaxb</argument> <argument>src/main/xsd/validation-configuration-1.1.xsd</argument> <argument>src/main/xsd/validation-mapping-1.1.xsd</argument> <argument>-b</argument> <argument>src/main/xjb/binding-customization.xjb</argument>         </arguments> </configuration> </plugin>  <plugin> <groupId>org.codehaus.mojo</groupId> <artifactId>build-helper-maven-plugin</artifactId> <executions> <execution> <id>add-source</id> <phase>generate-sources</phase> <goals> <goal>add-source</goal> </goals> <configuration> <sources> <source>target/generated-sources/jaxb</source> </sources> </configuration> </execution> </executions> </plugin>
Then it should work with java9.

Regards,
Hesham

**Comment by Toenex** [comment]
Thanks I'll give that a try.

**Comment by hczedik** [comment]
Opening the issue again, as it seems confirmed that the build doesn't work with Java 9. (Haven't tried it myself yet.)

**Comment by Ebeid** [comment]
Same with Java 10.

**Comment by mpkumar87** [comment]
Build fail with java 10.

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T00:03:14+05:30)
Maven home: C:\Program Files\apache-maven-3.5.4\bin\..
Java version: 10.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by gunterze** [comment]
Duplicates #335

**Comment by chandrapenumarthi** [comment]
Build failing with java 8 and maven 3.3.9
 BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.855 s
[INFO] Finished at: 2019-08-06T17:28:10+05:30
[INFO] Final Memory: 106M/765M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project dcm4chee-arc-query: Compilation failure: Compilation failure:
[ERROR] /home/chandramouli/Documents/git/dicom/techvedika-dicomviewer-server/dcm4chee-arc-light/dcm4chee-arc-query/src/main/java/org/dcm4chee/arc/query/impl/SeriesQuery.java:[257,59] cannot find symbol
[ERROR] symbol:   variable SeriesMetadataUpdateFailures
[ERROR] location: class org.dcm4che3.dict.archive.ArchiveTag
[ERROR] /home/chandramouli/Documents/git/dicom/techvedika-dicomviewer-server/dcm4chee-arc-light/dcm4chee-arc-query/src/main/java/org/dcm4chee/arc/query/impl/SeriesQuery.java:[278,64] cannot find symbol
[ERROR] symbol:   variable SeriesMetadataCreationDateTime
[ERROR] location: class org.dcm4che3.dict.archive.ArchiveTag
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dcm4chee-arc-query

**Comment by gunterze** [comment]
It actual works: https://travis-ci.org/dcm4che/dcm4che/builds/567841948
