### ISSUE TITLE
Support extracting Image Pixel Description Macro Attributes from MPEG-4 Part 14 files

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#239]
Support extracting [Image Pixel Description Macro Attributes](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#table_C.7-11c) from [MPEG-4 Part 14 files](https://en.wikipedia.org/wiki/MPEG-4_Part_14)  analogous to extraction from JPEG streams by [JPEGHeader](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/java/org/dcm4che3/imageio/codec/jpeg/JPEGHeader.java) and the extraction from MPEG2 streams by [MPEGHeader](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/java/org/dcm4che3/imageio/codec/mpeg/MPEGHeader.java).

Support:
- [x] MPEG-4 AVC/H.264 High Profile / Level 4.1 (Transfer Syntax: 1.2.840.10008.1.2.4.102)
- [x] MPEG-4 AVC/H.264 BD-compatible High Profile / Level 4.1 (Transfer Syntax: 1.2.840.10008.1.2.4.103 )
- [x] MPEG-4 AVC/H.264 High Profile / Level 4.2 for 2D (Transfer Syntax: 1.2.840.10008.1.2.4.104 )
- [ ] MPEG-4 AVC/H.264 High Profile / Level 4.2 for 3D (Transfer Syntax: 1.2.840.10008.1.2.4.105 )
- [x] MPEG-4 AVC/H.264 Stereo High Profile / Level 4.2 (Transfer Syntax: 1.2.840.10008.1.2.4.106 )
- [x] HEVC/H.265 Main Profile / Level 5.1 (Transfer Syntax: 1.2.840.10008.1.2.4.107 )
- [x] HEVC/H.265 Main 10 Profile / Level 5.1 (Transfer Syntax: 1.2.840.10008.1.2.4.108 )

Links
- [DICOM PS3.5](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_8.2.7)
- [ISO/IEC 14496-12](http://standards.iso.org/ittf/PubliclyAvailableStandards/c068960_ISO_IEC_14496-12_2015.zip)
- [ISO/IEC 14496-14](http://jchblog.u.qiniudn.com/doc/ISO_IEC_14496-14_2003-11-15.pdf)
- [Sample Videos](http://standaloneinstaller.com/blog/big-list-of-sample-videos-for-testers-124.html)
- [Java MP4 Parser](https://github.com/sannies/mp4parser)

**Comment by MarcoMatta** [comment]
Hi! News ?
