### ISSUE TITLE
dcm2jpg.bat - if called with params <folder> <folder>/<subfolder> creates deep folder tree

### ISSUE THREAD

**Issue by davew945** [dcm4che/dcm4che#242]
While testing 5.13.0, I called dcm2jpg.bat with c:\testDicoms c:\testDicoms\jpgs
and it created a deep tree c:\testDicoms\jpgs\jpgs\jpgs\...jpgs - I have no idea how deep but it
was very difficult to delete. it looks like other tools (dcm2dcm) use the same mechanism to handle destination folders. This was highly unexpected behavior.

**Comment by vrindanayak** [comment]
Not reproducible; neither with 5.13.0 nor with latest version 5.17.1.
