### ISSUE TITLE
Dcm4che-storescp breaks the images.

### ISSUE THREAD

**Issue by MikelGar** [dcm4che/dcm4che#251]
Hi everyone!

I am involved in a project where we are trying to move images from the Centricity PACS v.4.0 of General Electrics to a local server.
To that end, we used the command movescu along with storescp of dcm4che. However, the images seemed to be broken. 
We made additional tests, and proved that movescu works fine with other commands as for example storescp of DCMTK.
We assumed that the problem of the image breaking was related to the storescp but we do not find out the reason.
Any possible reasons or suggestions?

Thanks.

**Comment by hczedik** [comment]
Please use the dcm4che Google Group for questions:
https://groups.google.com/forum/#!forum/dcm4che

**Comment by H3ADLESS** [comment]
@MikelGar Have you posted your question in the google group? Could you post a link to your question? Or have you found another solution? I'm facing the same issue.
