### ISSUE TITLE
dcm2dcm compress DICOM file error

### ISSUE THREAD

**Issue by zhj2015** [dcm4che/dcm4che#259]
java.lang.IllegalArgumentException: Unknown compression type!
    at javax.imageio.ImageWriteParam.setCompressionType(ImageWriteParam.java:1023)

**Comment by nroduit** [comment]
Please start by explaining which command you are executing.
and which version of dcm4che, which version java and the OS with the architecture.

**Comment by zhj2015** [comment]
dcm4che：5.12.0，jdk：jdk1.7.0_75，window-x86-64

**Comment by nroduit** [comment]
It doesn't tell which compression type you expected.

Anyway, currently for compression, it is recommended to use a 32-bit Java Runtime on Widnows. You will find a lot of discussions on the Forum about this subject.

**Comment by zhj2015** [comment]
@nroduit   oh，thanks.
