### ISSUE TITLE
Missing classes in source code while binaries of same version (5.13.0) had the classes

### ISSUE THREAD

**Issue by venkattarigopula** [dcm4che/dcm4che#267]
The code from Tag 5.13.0 is not compiling because of missing various classes. For ex: org.dcm4che3.data.Tag and org.dcm4che3.data.UID classes are not available in source code. But the that 2 files are there in binaries of same version. These 2 classes are used in  org.dcm4che3.tool.common.CLIUtils class. These 2 missed classes are searched in the path 
dcm4che/dcm4che-core/src/main/java/org/dcm4che3/data/

Thanks for reading
-Venkat

**Comment by hczedik** [comment]
These classes get automatically generated during the build.
Just run
> mvn install

**Comment by venkattarigopula** [comment]
Thank you @hczedik for your response. I will check and reply the same
