### ISSUE TITLE
dcm2jpg throws UnsatisfiedLinkError: no opencv_java in java.library.path

### ISSUE THREAD

**Issue by frickt** [dcm4che/dcm4che#274]
Since Version 5.13.0, dcm2jpg throws UnsatisfiedLinkError: no opencv_java in java.library.path on Windows X64, seems to be an issue with the new opencv_java.dll in lib\win-x86_64.
Version <= 5.12.0 works.

**Comment by yongliangZhang** [comment]
这个问题我通过工具包测试DICOM压缩包发现了了，需要将 lib目录下opencv_java.dll 文件放入JDK jre bin 目录下

**Comment by victorcruz86** [comment]
Hello, I just installed Windows 10 and I'm having the same problem, I tried to find a solution but I can't find one, please if someone can help.

**Comment by yongliangZhang** [comment]
@ymirabalg @carmenates09  If you are using win10 system, please put the opencv_java.dll file under the win_86_64 folder under the lib folder of the dcm4chee-5.12.xx version file into the jre/bin directory of your system JDK version directory.

**Comment by ddbxyrj** [comment]
@yongliangZhang 请问 这个新版的工具包如何使用maven 重构呢 用eclipse 的 和 maven 3.5 都试过  而且也用了代理 都有错误 谢谢

**Comment by rrzaripov** [comment]
@gunterze I think problem is [here](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-assembly/src/bin/dcm2jpg.bat#L64):

`set JAVA_OPTS=%JAVA_OPTS% "-Djava.library.path=%JAVA_LIBRARY_PATH%"`

Double quote corrupt the environment variable value. Without quotes works for me (under Windows):

`
set JAVA_OPTS=%JAVA_OPTS% -Djava.library.path=%JAVA_LIBRARY_PATH%
`

And second interesting moment, is not paired double quote [here](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-assembly/src/bin/dcm2jpg.bat#L67).

**Comment by gunterze** [comment]
I removed the incorrect quotes in dcm2dcm.bat, dcm2jpg.bat, storescu.bat which may solve the problem on Windows.

**Comment by brazier-bear** [comment]
opencv_java.dll哪里可以下载或者是哪个jar文件中用到的呢

**Comment by brazier-bear** [comment]
@gunterze where is opencv_java.dll？I use 5.14.1,but still has this exception.

**Comment by Chappie22** [comment]
> > @gunterze where is opencv_java.dll？I use 5.14.1,but still has this exception.
> 
> It should be located in your dcm4che installation directory: dcm4che-home/lib/win-x86_64/opencv_java.dll

+1 Works for me, thanks

**Comment by Abdelhad1Belaid** [comment]
I'm using fedora linux and i installed the opencv-java package using the package manager "dnf" then i got the same error so i just created some directories /usr/java/packages/lib then i copied the whole content of the /lib/java/ into the dirs that created . and it SOLVED my probled

give it a try
