### ISSUE TITLE
jpg2dcm: missing file operand

### ISSUE THREAD

**Issue by flexpeace** [dcm4che/dcm4che#280]
When l run the command below on Linux, l get the error "jpg2dcm: missing file operand"

```
jpg2dcm --no-app -a PatientName=Simson^Homer -a PatientSex=M
homer.jpg image.dcm
```

It works if l omit -a PatientName=Simson^Homer -a PatientSex=M

Can someone help me please?

**Comment by vrindanayak** [comment]
Please try : 
jpg2dcm --no-app -a PatientName=Simson^Homer -a PatientSex=M -- homer.jpg image.dcm
I've updated the Readme.
