### ISSUE TITLE
stow-rs utility: provide sample metadata for Secondary Capture and VL Photographic Images and for Encapsulated PDFs

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#291]
Provide sample metadata for
- [Secondary Capture Image](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_A.8.1)
- [VL Photographic Image](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_A.32.4)
- [Encapsulated PDF](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_A.45.1) with  _Modality (0008,0060)_ = `DOC` 

and provide CL options `--sc`, `--xc`, `--pdf` for selecting that metadata.

**Comment by vrindanayak** [comment]
Make the CL options `--sc`, `--xc` and `--pdf` mutually exclusive.
