### ISSUE TITLE
org.dcm4che3.data.Tag  被作者吃了么？

### ISSUE THREAD

**Issue by SpiritZhangYP** [dcm4che/dcm4che#295]
还有 org.dcm4che3.data.UID， 源码不完全开放么？

**Comment by SpiritZhangYP** [comment]
dcm4che-core missing Tag and UID class

**Comment by hczedik** [comment]
These classes get generated during the build process.
Just run:
```
mvn install
```

**Comment by jayzhk** [comment]
@SpiritZhangYP , Tag 和UID class源文件 是在mvn install 的时候动态生成的。
参考
![image](https://user-images.githubusercontent.com/8359838/41029365-caee14fe-697b-11e8-88b0-1b7fd327b7d9.png)
