### ISSUE TITLE
dcm2Jpg 创建对象失败

### ISSUE THREAD

**Issue by SpiritZhangYP** [dcm4che/dcm4che#300]
我想使用dcm2Jpg生成缩略图：
File sorceFile = new File("D:/dicom/1/3");
			File destFile = new File("D:/1.jpg");
			Dcm2Jpg dj  = new Dcm2Jpg();
			dj.convert(sorceFile, destFile);
但是Debug时，Dcm2Jpg dj  = new Dcm2Jpg();， 创建对象会失败，哪次都会跳到 ClassLoader.class
我这样创建对象有问题么？还是环境不对？

**Comment by SpiritZhangYP** [comment]
I want  to generate a thumbnails from a dcm:
File sorceFile = new File("D:/dicom/1/3");
File destFile = new File("D:/1.jpg");
Dcm2Jpg dj = new Dcm2Jpg();
dj.convert(sorceFile, destFile)
but when I Debuging,  Dcm2Jpg dj = new Dcm2Jpg(); Failed to create object， It will go to ClassLoader.class
Thank you very much

**Comment by hczedik** [comment]
For questions please use the dcm4che Google Group: https://groups.google.com/forum/#!forum/dcm4che

Thank you!
