### ISSUE TITLE
whether dcm4che can converter ecg dcm to jpg or pdf ?  which class can do?

### ISSUE THREAD

**Issue by yangbaiyun** [dcm4che/dcm4che#317]
whether dcm4che can converter ecg dcm to jpg or pdf ?  which class can do?where i can find some documents to study about ecg at this project?

**Comment by gunterze** [comment]
Post questions about dcm4che/dcm4chee-arc to the [dcm4che Google Group](https://groups.google.com/forum/#!forum/dcm4che)
