### ISSUE TITLE
About lib opencv in dcm2jpg

### ISSUE THREAD

**Issue by NoviaRick** [dcm4che/dcm4che#322]
in package org.dcm4che3.opencv--->NativeJLSImageWriter.java
It use opencv.jar file whlile import org.opencv.imgcodecs.Imgcodecs;
but how can I import Imgcodecs.DICOM_IMREAD_SIGNED and Imgcodecs.DICOM_IMREAD_UNSIGNED?
It seems not in opencv.jar file, what can I do now ?
also
`Imgcodecs.DICOM_IMREAD_SIGNED

Imgcodecs.DICOM_IMREAD_UNSIGNED
     
Imgcodecs.ILV_SAMPLE     
Imgcodecs.dicomJpgWrite(mat, dicomParams, "")`

**Comment by nroduit** [comment]
This is the place to report issues, not for questions. So if you notice an issue please elaborate.

**Comment by gunterze** [comment]
Please post questions to the [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che)
