### ISSUE TITLE
Support encoding / decoding of NaN, Infinity, -Infinity values of attributes with VR = FL or FD by JSONWriter/JSONReader

### ISSUE THREAD

**Issue by wtellis** [dcm4che/dcm4che#329]
Support encoding / decoding of `NaN`, `Infinity`, `-Infinity` values of attributes with VR = FL or FD  by `JSONWriter/JSONReader`:

- encode `NaN` as `null`
- encode 'Infinity' as `3.4028234663852886E38` (VR=FL) or `1.7976931348623157E308`  (VR=FD)
- encode '-Infinity' as `-3.4028234663852886E38` (VR=FL) or `-1.7976931348623157E308`  (VR=FD)
- decode `null` as `NaN`
- decode `3.4028234663852886E38` (VR=FL) or `1.7976931348623157E308`  (VR=FD) as 'Infinity'
- decode `-3.4028234663852886E38` (VR=FL) or `-1.7976931348623157E308`  (VR=FD) as '-Infinity'

Avoids:

> The `JSONWriter.writeDoubleValues` method throws a `java.lang.NumberFormatException` if the call to `vr.toDouble(val, bigEndian, i, 0)` returns `NaN`.  This stops the creation of the JSON object. `JSONWriter` should be able to gracefully handle `NaN` values (e.g. output `null` or skip that value).

**Comment by gunterze** [comment]
Will wait how the issue will be solved in the specification. Posted: https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKQgzrSgNRjXtzsMGhhPQjdWT
