### ISSUE TITLE
Missing implementation "org.dcm4che3.data.DicomObject"

### ISSUE THREAD

**Issue by sankar1204** [dcm4che/dcm4che#334]
Here : https://dcm4che.atlassian.net/wiki/spaces/d2/pages/1835034/Reading+DICOM+files
cook book example says that we can use DicomObject implementation, but I don't see it in the archive.

Can someone tell me where / how to locate it?

**Comment by gunterze** [comment]
https://dcm4che.atlassian.net/wiki/spaces/d2/pages/1835034/Reading+DICOM+files refers  [dcm4che 2.x](https://sourceforge.net/p/dcm4che/svn/HEAD/tree/dcm4che2/) which is no longer maintained by myself.
