### ISSUE TITLE
Build fails with Java 10

### ISSUE THREAD

**Issue by mpkumar87** [dcm4che/dcm4che#335]
Hi,

Build fail with java 10.

[ERROR] /C:/xampp/htdocs/dcm4che-master/dcm4che-audit/src/main/java/org/dcm4che3/audit/AuditMessages.java:[942,32] cannot find symbol
symbol: class AuditMessage

[INFO] Reactor Summary:
[INFO]
[INFO] dcm4che DICOM toolkit and utilities 5.14.0 ......... SUCCESS [ 1.805 s]
[INFO] dcm4che-audit ...................................... FAILURE [ 27.462 s]

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T00:03:14+05:30)
Maven home: C:\Program Files\apache-maven-3.5.4\bin..
Java version: 10.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Please guide me to resolve this issue.

Thanks.

**Comment by nicomlas** [comment]
Hi,
The problem is that maven doesn't trigger the source generation.
Do it manually or add the phase tag in the execution part in the dcm4che-audit/pom.xml :

` <executions>
          <execution>
            <id>xjc</id>
            <goals>
              <goal>xjc</goal>
            </goals>
            <phase>generate-sources</phase>
          </execution>
        </executions>`

Then, execute 'mvn install', it should work.
Regards.

**Comment by gunterze** [comment]
Related: mojohaus/jaxb2-maven-plugin#104
