### ISSUE TITLE
Is there any documentation worth while on how to use this?

### ISSUE THREAD

**Issue by toymachiner62** [dcm4che/dcm4che#349]
This library looks fabulous...until you actually try to use it and there are literally zero instructions. 

Is this meant to be a Java library for developers to consume? If so that's not clear in any way whatsoever. 

I end up at https://dcm4che.atlassian.net/wiki/spaces/d2/overview which tells me there is a new version so i click the link and end up at https://dcm4che.atlassian.net/wiki/spaces/lib/overview. Great i click the link to documentation which takes me to https://github.com/dcm4che/dcm4che/blob/master/README.md. uhhh ok a shit ton of modules maybe  ? Idk well i'm trying to convert a dicom image to a jpg so let me click the dcm2jpg link to see if there's any documentation. https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-dcm2jpg/README.md Um shows me the help of a command line tool? I thought this was a java library considering if i google "dcm4che maven" there's all kinds of links. 

What the actual FUCK!!!

**Comment by hczedik** [comment]
Currently the code is the documentation.
Check the code of the dcm2jpg command line tool, to see how you can use the library to do what you need.
But, totally agreed that there should be more documentation. This is an open source project and you are very welcome to contribute.
In general for further discussions and questions please use the dcm4che Google Group:
https://groups.google.com/forum/#!forum/dcm4che
(and not the bug tracker please).

**Comment by umeshravuru** [comment]
dcm2jpg readMe says this:
`Example: dcm2jpg img.dcm img.jpg`
Where should I run this command.
