### ISSUE TITLE
Create issue template to direct users to google group

### ISSUE THREAD

**Issue by blairconrad** [dcm4che/dcm4che#351]
Per https://github.com/dcm4che/dcm4che/issues/349#issuecomment-424596989, the GitHub issue tracker is to be used to track bugs, not for "discussions and questions". An [issue template](https://help.github.com/articles/about-issue-and-pull-request-templates/) could be used to provide this information to users as they are creating their issue, rather than forcing them to wait for a moderator (or other community member) to see their issue and chime in.

It seems that having multiple issue templates is the preferred mechanism now, and that must be done by maintainers, but if you only want a single issue template, I'd be happy to contribute a PR. Just say the word.

**Comment by gunterze** [comment]
Done.
