### ISSUE TITLE
new DicomInputStream(File file) of non DCM File is not closing the FileInputStream

### ISSUE THREAD

**Issue by atouboul** [dcm4che/dcm4che#352]
Hello,

When making a new DicomInputStream(File file) on a non DICOM File, the FileInputStream  made on this file is not closed after running method guessTransferSyntax() which returns an DicomStreamException.

Would it be possible to have this FileInputStream closed in a future release ?

Thanks and regards,

Arnaud

**Comment by gunterze** [comment]
Should be fixed by #151 since 5.12.1 - if not, reopen that issue
