### ISSUE TITLE
Can't run PACS on DSM6.1 after upgrade to the newest version

### ISSUE THREAD

**Issue by rukh2018** [dcm4che/dcm4che#353]
Hi guys!
I found a new problem after upgraded PACS to the newest version on a cracked synology DS3615xs with DSM6.1. The PACS system can't run even after I reboot the DSM. After checking Docker, a new container named "synology-slapd-dcm4chee" was found installed. Yet it cannot run. Any advices or instructions on this? Thanks!

**Comment by hczedik** [comment]
Hello @rukh2018,
this is the bug tracker for the dcm4che Library & Toolkit. You probably wanted to open a bug for the [dcm4chee Archive](https://github.com/dcm4che/dcm4chee-arc-light).
In general please use the dcm4che Google Group for questions: http://groups.google.com/group/dcm4che
