### ISSUE TITLE
Trouble Reading And Image

### ISSUE THREAD

**Issue by jconinc** [dcm4che/dcm4che#358]
So I'm trying to put multiple images into a dicom file. The reason I'm doing this is to add video into a dicom file. I split the video into frames and then add the frames. I looked at an dcm4che2 example and adapted it to dcm4che3. Below is my code.  I get an exception at the last line. If you can see below, I have tried different image input streams and none seem to work and actually ones like the SegmentedInputStream gave me null. If my entire approach is wrong, please let me know. I couldn't find any documentation.

	        // Status message
	        System.out.println("Creating Multiframe File...");
	        System.out.println(System.getProperty("java.library.path"));
	        System.loadLibrary("opencv_java");
	        // Get an image sample from the array of images
	        String sourceSyntax = "1.2.840.10008.1.2.4.50";
	        // Create DICOM image writer instance and set its output
	        ImageWriterFactory.ImageWriterParam param = ImageWriterFactory.getDefault().getImageWriterParam(sourceSyntax);
	        ImageWriter writer = ImageWriterFactory.getImageWriter(param);
	        FileImageOutputStream output = new FileImageOutputStream(dest);
	        writer.setOutput(output);
	        //FileInputStream fIn = new FileInputStream(frames[0]);
	        int read;
	        //byte[] allBytes = FileUtils.readFileToByteArray(frames[0]);
	        	
	        //PatchJPEGLSImageInputStream sIn = new PatchJPEGLSImageInputStream(new FileImageInputStream(frames[0]), null);
	        //SegmentedInputImageStream sIn = new SegmentedInputImageStream(allBytes);
	        System.loadLibrary("lib/win-x86_64/opencv_java");
	        BufferedImage sample = ImageIO.read(new FileImageInputStream(frames[0]));

**Comment by gunterze** [comment]
Please post question to https://groups.google.com/forum/#!forum/dcm4che
