### ISSUE TITLE
build&compile

### ISSUE THREAD

**Issue by cognaclee** [dcm4che/dcm4che#359]
How can we compile the source code, can we have a simple explanation?

**Comment by hczedik** [comment]
From the README file:
https://github.com/dcm4che/dcm4che/blob/master/README.md

After installation of Maven 3, run:

    mvn install

Note: Please use the dcm4che Google Group for questions: https://groups.google.com/forum/#!forum/dcm4che

**Comment by cognaclee** [comment]
> From the README file:
> https://github.com/dcm4che/dcm4che/blob/master/README.md
> 
> After installation of Maven 3, run:
> 
> ```
> mvn install
> ```
> Note: Please use the dcm4che Google Group for questions: https://groups.google.com/forum/#!forum/dcm4che

thank you
