### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by YuQiuGit** [dcm4che/dcm4che#360]
Exception: Could not find artifact org.weasis.opencv:weasis-opencv-core:jar:3.0.2-rc1
Where is the Repository Address of this?

**Comment by gunterze** [comment]
```xml
    <repository>
      <id>nroduit-mvn-repo-master</id>
      <url>https://raw.github.com/nroduit/mvn-repo/master/</url>
    </repository>
```
Please post questions to  https://groups.google.com/forum/#!forum/dcm4che
