### ISSUE TITLE
Unable to write a previously read `UN` value from DICOM JSON

### ISSUE THREAD

**Issue by adamRenny** [dcm4che/dcm4che#372]
**Describe the bug**
After successfully reading in DICOM JSON that includes a `UN` value representation that uses a Base64 encoded `Value`, dcm4che throws a `java.lang.ClassCastException`. A description of that representation can be seen in [F.2.2 DICOM JSON Model Object Structure](http://dicom.nema.org/Dicom/2013/output/chtml/part18/sect_F.2.html#sect_F.2.2).

**To Reproduce**
1. Using limited DICOM JSON such as:
```
[
    {
        "00190001": {
            "vr": "UN",
            "Value": [
                "SGVsbG8sIHdvcmxkIQ=="
            ]
        }
    }
]
```
2. Read in the string using a JSON parser
3. Write the now `java.util.List<org.dcm4che3.data.Attributes>` out

**Expected behavior**
Able to write out a `UN` value that was read in from DICOM JSON.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Java JDK: OpenJDK 1.8.0 build 181
 - dcm4che Version: 5.14.0 `core` & `json`

**Additional context**
Example of code for processing, where `INSTANCE_JSON` is a JSON string similar to the above:
```
    public void readWriteTest() {
        List<Attributes> results = new ArrayList<>();
        JsonParser parser = Json.createParser(new ByteArrayInputStream(INSTANCE_JSON.getBytes()));
        JSONReader reader = new JSONReader(parser);
        reader.readDatasets((fmi, data) -> results.add(data));

        Writer writer = new StringWriter();
        try (JsonGenerator generator = Json.createGenerator(writer)) {
            JSONWriter jsonWriter = new JSONWriter(generator);
            generator.writeStartArray();
            results.forEach(jsonWriter::write);
            generator.writeEnd();
            generator.flush();
        }
    }
```

**Comment by gunterze** [comment]
UN Values have to be base64 encoded in JSON property `InlineBinary`, **not** as array element of `Value`. s. [DICOM PS3.18, F.2.2 DICOM JSON Model Object Structure](http://dicom.nema.org/Dicom/2013/output/chtml/part18/sect_F.2.html#sect_F.2.2), which actually works:
```console
gunter@gunter-nb:~/work/dcm4che$ json2dcm -j - -o /tmp/test.dcm
[
    {
        "00190010": {
            "vr": "LO",
            "Value": [
                "PRIVATE_CREATOR_ID"
            ]
        },
        "00191001": {
            "vr": "UN",
            "InlineBinary": "SGVsbG8sIHdvcmxkIQ=="
        }
    }
]
gunter@gunter-nb:~/work/dcm4che$ dcmdump /tmp/test.dcm
0: (0019,0010) LO #18 [PRIVATE_CREATOR_ID] PrivateCreatorID
26: (0019,1001) UN #14 [72\101\108\108\111\44\32\119\111\114\108\100\33\0] 
```

**Comment by adamRenny** [comment]
Thanks for the clarification. I had missed the phrasing of the list of supported `vr`s for `Value`. Apologies on that mistake and thank you again for the clarification!
