### ISSUE TITLE
Dcm2Jpg: create destination directory if directory doesn't exist

### ISSUE THREAD

**Issue by simur407** [dcm4che/dcm4che#387]
**Description**
When first parameter is a directory of dcm files, and second parameter is name of destination directory, but destination directory does not exist, there is printed error message: "target <dest dir> is not a directory". I checked source code and found corresponding line:
`Dcm2Jpg.java:309 File dest = new File(argList.get(argc-1));`
`Dcm2Jpg.java:310 if ((argc > 2 || new File(argList.get(0)).isDirectory()) && !dest.isDirectory())`
There is check if `dest` is a directory, but `isDirectory()`, as we can see in [docs](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#isDirectory()) will return `false` because 

> returns true if and only if the file denoted by this abstract pathname **exists** and is a directory; false otherwise

What's more, I found that it was indeed intended to allow non existing directories, because in lines:
`Dcm2Jpg.java:335 private void mconvert(File src, File dest) {`
`Dcm2Jpg.java:336       if (src.isDirectory()) {`
`Dcm2Jpg.java:337            dest.mkdir();`

There is call for `dest.mkdir()`

**To Reproduce**
1. Run dcm2jpg with first argument as real dicom directory path and second with some name the directory should have
For windows it will be `./dcm2jpg.bat <existing dir with dicom files> <some non existing dest dir>
2. See message "target <some non existing dest dir> is not a directory"

**Expected behavior**
Directory <some non existing dest dir> is created and all jpg files processed from source directory are saved there.

**Comment by gunterze** [comment]
The current behavior, to require an existing target directory, but create sub-directory in it, is intended.
