### ISSUE TITLE
NoClassDefFoundError: org/dcm4che3/imageio/stream/ImageInputStreamAdapter 

### ISSUE THREAD

**Issue by cauyyl** [dcm4che/dcm4che#389]
On maven project , i have import dcm4che5.14.1 from local folder,and on my local machine,it worked well with
 `dcm2Jpg.initImageWriter("JPEG", null, null, null, 1l);`
` dcm2Jpg.convert(src, dest);`

But on ECS , i got  NoClassDefFoundError.I have no idea about how to fix it and now im trying to change dcm4che3 version

**Comment by hczedik** [comment]
Please post questions to https://groups.google.com/forum/#!forum/dcm4che
