### ISSUE TITLE
wado-rs util: use UID as file name

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#391]
- [x] use UID from path component as file name (instead `part`)
- [x] start file name number suffix with 1 instead of 0. 
- [x] use leading zeros to extend the  number suffix to 3 digits.
- [x] pass URL as CLI argument instead as option `--url`
- [x] support to specify multiple URLs to invoke multiple WADO-RS requests
- [x] fix the currently not working option `out-dir`
- [x] fix the currently not working `retrieve metadata as json`
- [x] support `a (=accept)` option to specify only the subtype instead of complete required accept header (for eg. use `jpeg` instead of `multipart/related;type=image/jpeg` and so on for other types)
- [x] suppress misleading
  ```
  17:18:12,249 WARN  - Missing Boundary Parameter in response Content Type
  ```
  on HTTP error. Change to 
````
  18:23:12,190 WARN  - Invalid response. Unpacking of parts not possible.
````

**Comment by vrindanayak** [comment]
- [x] make `a (=accept)` option as optional, if none is specified use wildcard `*`
- [x] add logging also for extraction of metadata as json
- [x] support `--header` option so that user can decide if Accept shall be sent in Request Header or as query parameter appended to the URL
