### ISSUE TITLE
setSpecificCharacterSet() in Attributes.java does not work properly

### ISSUE THREAD

**Issue by caribbeann** [dcm4che/dcm4che#403]
The method in Attributes.java class: 

_public void setSpecificCharacterSet(String... codes) {
        decodeStringValuesUsingSpecificCharacterSet();
        setString(Tag.SpecificCharacterSet, VR.CS, codes);
}_

does decoding first and then sets the tag. Shouldnt it first set the TAG and then attempt to decode with the new standard?

**Comment by gunterze** [comment]
No. You have to decode the binary to Strings with the previous Character Set. The new Character Set will be effective on encoding the Strings to binary on writing the Attributes into a DicomOutputStream.
