### ISSUE TITLE
dcm2dcm fails to find ImageWriter for format jpeg

### ISSUE THREAD

**Issue by jssuttles** [dcm4che/dcm4che#41]
Mac
<img width="806" alt="screen shot 2017-03-15 at 5 53 23 pm" src="https://cloud.githubusercontent.com/assets/8527741/23972580/c3248732-09a8-11e7-8013-0aa9bd9235ea.png">

Windows
<img width="591" alt="screen shot 2017-03-15 at 5 56 58 pm" src="https://cloud.githubusercontent.com/assets/8527741/23972605/d4f0569e-09a8-11e7-849f-9c851d95b199.png">

Tried this with various other syntaxes and got the same result. I'm looking for j2ki in particular. The input file is a multiframe mammo. Have also tried it with a single frame dicom file.

**Comment by hczedik** [comment]
Hi jsstuttles,

I assume you use a 64bit Java VM on Windows.
dcm4che uses ImageIO and that doesn't work for 64bit on Windows. See e.g. http://stackoverflow.com/questions/5207145/jai-and-imageio-for-64-bit-windows

Try installing a 32bit Java VM on Windows, or use Linux (both 32bit and 64bit are working there).
