### ISSUE TITLE
Disable detection of end of frame in EncapsulatedPixelDataImageInputStream for RLE multiframe images

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#412]
According [DICOM PS3.5, A.4.2 RLE Image Compression](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_A.4.2)
> Each frame shall be encoded in one and only one Fragment

Therefore for RLE, there is no need for the detection of end of frame in EncapsulatedPixelDataImageInputStream - besides the used algorithm is anyway not appropriate for RLE.

s.o. dcm4che/dcm4chee-arc-light#752

**Comment by hczedik** [comment]
I would disable the end-of-frame-detection for EVERYTHING except the JPEG transfer syntaxes.

**Comment by gunterze** [comment]
That's implicitly the case after it's disabled for RLE. For MPEG there is only one data fragment.

**Comment by hczedik** [comment]
True, but on the other hand, why make it *implicit* if you could also *explicitly* list the JPEG transfer syntaxes? Also, in theory as "Privately defined Transfer Syntax Names may also be used", for those it could also cause problems, as well as for future standard transfer syntaxes.
