### ISSUE TITLE
jpg2dcm not update some basic tage like TransferSyntaxUID,SamplesPerPixel,PhotometricInterpretation

### ISSUE THREAD

**Issue by deepakaneja** [dcm4che/dcm4che#455]
![Updatedtad](https://user-images.githubusercontent.com/11642849/58081867-70112b00-7bd3-11e9-90f4-5c653899db3a.png)

**Comment by deepakaneja** [comment]
![Updatedtad](https://user-images.githubusercontent.com/11642849/58081802-4f48d580-7bd3-11e9-984c-8ae9a5c5ac26.png)

**Comment by vrindanayak** [comment]
This is the Transfer Syntax UID used by default for MPEG2 files. The SamplesPerPixel and PhotometricInterpretation are set in the attributes, both for [Jpegs](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/java/org/dcm4che3/imageio/codec/jpeg/JPEGHeader.java) and [Mpeg2](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/java/org/dcm4che3/imageio/codec/mpeg/MPEGHeader.java). You may also use [dcmdump tool](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-dcmdump/README.md) to see the contents of the DICOM file.
The xml files are only supported for [providing sample metadata for Secondary Capture and VL Photographic Images](https://github.com/dcm4che/dcm4che/issues/292)

Please ask further questions in [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)
