### ISSUE TITLE
Avoid duplicate PIDs returned by IDWithIssuer.pidsOf(Attributes)

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#529]
If the _Patient ID_ in the root data set matches with any of the _Patient IDs_ in the _Other Patient ID Sequence_, only return the more qualified _Patient ID_ by `IDWithIssuer.pidsOf(Attributes)`, were a _Patient ID_ is concerned as "more qualified", if
- it has **either** an _Issuer Of Patient ID_ **or** an _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_ and the other _Patient ID_ has **neither** an _Issuer Of Patient ID_ **nor** an _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_ , or
- it has an _Issuer Of Patient ID_ **and** an _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_ and the other _Patient ID_ has only an _Issuer Of Patient ID_ **or** an _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_, but not both, or
- it has an _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_ and the other _Patient ID_ has only an _Issuer Of Patient ID_, but no  _Universal Entity ID_ in its _Issuer of Patient ID Qualifiers Sequence_.

**Comment by MarkDechamps** [comment]
Is this correct Gunter ? 
e.g If an mwl query is sent in specifying e.g only the namespace id for OtherPatientIdSequence (specifying nothing for main id). Then in the response all the ids in OtherPatientIdSequence should have only namespace (no issuer). 
The fact that the main id has namespace and universal id is of no importance. In your solution there will be 1 id in otherPatientIdSequence having both namespace and universal id and all the others not.

**Comment by gunterze** [comment]
The result of my solutions differs from yours (#526) only in the case, if the "main" Patient ID is "more" qualified, than a matching Other Patient ID: In that case #526 would have included the Other Patient ID, where this solution will include the Patient ID from the root dataset.
