### ISSUE TITLE
JPG2DCM conversion error

### ISSUE THREAD

**Issue by umeshravuru** [dcm4che/dcm4che#531]
**Describe the bug**
I am getting the below error when I try to convert jp2 image to dcm using JPG2DCM jar

jpg2dcm: null
java.lang.NullPointerException
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm$FileType.valueOf(Jpg2Dcm.java:327)
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:224)
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:182)
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.main(Jpg2Dcm.java:110)

**To Reproduce**
1. Build the jar and
2. Run   java -jar jpg2dcm.jar -f ./932058/DICOM/20130304180841.104.1436167.xml ./932058/20130304180841.104.1436167.rst.jpg 20130304180841.104.1436167.dcm

**Expected behavior**
Produce a dcm file as the output
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - iOS
 - N/A
 - Lastest

**Comment by vrindanayak** [comment]
Perhaps your jp2 file is returning null content type.

I've added a [commit](https://github.com/dcm4che/dcm4che/commit/46f3cd1344cbfbc45dbaf710cd976b653bf813f5) to also handle exception for `null` content types returned, but this fix will only show an error message with the content type returned by your file and  not convert the JPEG2000 (if content type was null and/or parsing is not supported by JPEGParser) to DICOM file.

Please post further questions to [dcm4che user forum](https://groups.google.com/forum/?hl=en#!forum/dcm4che)

**Comment by Gokcann** [comment]
Hi,

Did you solve this problem?
