### ISSUE TITLE
Failed to convert MEEG video using jpg2dcm

### ISSUE THREAD

**Issue by lixin1984** [dcm4che/dcm4che#551]
**Describe the question**
Using jpg2dcm, I was unable to complete the conversion of mpeg files.  Please help me, thank you!

**Screenshots**
![image](https://user-images.githubusercontent.com/55874294/65757746-561bc200-e14a-11e9-8cda-37a2b77eee7c.png)

**Comment by gunterze** [comment]
Can you provide me the MPEG2 file somewhere?

**Comment by lixin1984** [comment]
> Can you provide me the MPEG2 file somewhere?

**Comment by lixin1984** [comment]
> Can you provide me the MPEG2 file somewhere?

I have another problem when using DCM4CHEE. Could you please tell me how to solve it? Thank you very much！
[https://github.com/dcm4che/dcm4chee-arc-light/issues/2175](url)

**Comment by gunterze** [comment]
Reopened #521 
Will be fixed in 5.19.0
