### ISSUE TITLE
DCM4CHE doesn't keep block identification code for private elements

### ISSUE THREAD

**Issue by homerocda** [dcm4che/dcm4che#552]
**Describe the bug**
We have an issue where the server may change data attribute tags when importing objects. One element with tag (3773,2030) was changed to (3773,1030). In another file, (3773,3025) was changed to (3773,1025). The culprit was found to be the way that DCM4CHE handles private tags.

**To Reproduce**
This test fails:

       Attributes original = new Attributes();
        original.setString("PrivateCreatorA", 0x00991001, VR.LO, "0099xx01A");
        original.setString("PrivateCreatorB", 0x00992001, VR.LO, "0099xx01B");
        original.setString("PrivateCreatorC", 0x00993001, VR.LO, "0099xx01C");

        Attributes selection = new Attributes();
        selection.setNull("PrivateCreatorA", 0x00991001, VR.LO);
        selection.setNull("PrivateCreatorC", 0x00993001, VR.LO);

        Attributes filtered = new Attributes();
        filtered.addSelected(original, selection);

        assertTrue("Attributes should keep the element tag for PrivateCreatorA", filtered.contains(0x00991001)); // PASSES
        assertTrue("Attributes should keep the element tag for PrivateCreatorC", filtered.contains(0x00993001)); // FAILS!

**Expected behavior**
Test should pass and filtered should contain the correct tags.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
When parsing a DICOM object, private creator elements are ignored at first. Only when the first private data element is received it will insert the private creator tag. It does so by taking the group number from the data element tag, appending a 0x10 suffix to it and checking for conflicts.   If a conflict is found, the tag is incremented until a free private element block is found. The private element block number is completely ignored in this process. Refer to (https://github.com/dcm4che/dcm4che/blob/abd3179558166dc8e03d1a897352efb96f46a9d5/dcm4che-core/src/main/java/org/dcm4che3/data/Attributes.java#L406)

**Comment by hczedik** [comment]
Might be related to https://dcm4che.atlassian.net/browse/LIB-362

**Comment by homerocda** [comment]
Hi @hczedik. #40 is related to this. We are using the generic-config branch.

**Comment by gunterze** [comment]
Fixed by #554
