### ISSUE TITLE
jpg2dcm 5.17.0+: Incorrect jpeg conversion

### ISSUE THREAD

**Issue by jimOnAir** [dcm4che/dcm4che#560]
Then I trying to convert jpeg to dcm with jpg2dcm 5.17.0+, I'm getting corrupted images with (0028,0010), (0028,0011) mixed up.  
I've tried the following command with different versions(5.16.3, 5.17.0, 5.18.1, 5.19.0):

```console
jpg2dcm Sample_0.jpg <jpg2dcm version>.dcm
```
And get the following output:  
[dcm.zip](https://github.com/dcm4che/dcm4che/files/3714291/dcm.zip)

```console
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by gunterze** [comment]
Caused by #561
