### ISSUE TITLE
ApacheDS cannot start after import of the dcm4che.ldif

### ISSUE THREAD

**Issue by cristianferencz** [dcm4che/dcm4che#572]
bin/apacheds-2.0.0.AM25-default console
Running ApacheDS - default...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | [11:05:35] ERROR [org.apache.directory.api.ldap.model.entry.DefaultAttribute] - ERR_13215_VALUE_EXPECT_STRING The value is expected to be a String
jvm 1    | [11:05:35] ERROR [org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader] - ERR_16009_LDIF_LOAD_FAIL Failed to load schema LDIF file cn=dcm4che.ldif
jvm 1    | org.apache.directory.api.ldap.model.exception.LdapInvalidAttributeValueException: ERR_13215_VALUE_EXPECT_STRING The value is expected to be a String
jvm 1    | 	at org.apache.directory.api.ldap.model.entry.DefaultAttribute.getString(DefaultAttribute.java:517)
jvm 1    | 	at org.apache.directory.api.ldap.model.schema.registries.AbstractSchemaLoader.getSchema(AbstractSchemaLoader.java:171)
jvm 1    | 	at org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader.initializeSchemas(LdifSchemaLoader.java:141)
jvm 1    | 	at org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader.<init>(LdifSchemaLoader.java:111)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.initSchemaManager(ApacheDsService.java:288)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:183)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:152)
jvm 1    | 	at org.apache.directory.server.wrapper.ApacheDsTanukiWrapper.start(ApacheDsTanukiWrapper.java:175)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788)
jvm 1    | [11:05:35] ERROR [org.apache.directory.server.wrapper.ApacheDsTanukiWrapper] - Failed to start the service.
jvm 1    | org.apache.directory.api.ldap.model.exception.LdapInvalidAttributeValueException: ERR_13215_VALUE_EXPECT_STRING The value is expected to be a String
jvm 1    | 	at org.apache.directory.api.ldap.model.entry.DefaultAttribute.getString(DefaultAttribute.java:517)
jvm 1    | 	at org.apache.directory.api.ldap.model.schema.registries.AbstractSchemaLoader.getSchema(AbstractSchemaLoader.java:171)
jvm 1    | 	at org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader.initializeSchemas(LdifSchemaLoader.java:141)
jvm 1    | 	at org.apache.directory.api.ldap.schema.loader.LdifSchemaLoader.<init>(LdifSchemaLoader.java:111)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.initSchemaManager(ApacheDsService.java:288)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:183)
jvm 1    | 	at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:152)
jvm 1    | 	at org.apache.directory.server.wrapper.ApacheDsTanukiWrapper.start(ApacheDsTanukiWrapper.java:175)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788)
wrapper  | <-- Wrapper Stopped

 head -n1 ldap/apacheds/dcm4che.ldif
# Generated by Apache Directory Studio on July 25, 2019, 11:02:02 AM

**Comment by vrindanayak** [comment]
Is not reproducible. Try with [Running ApacheDS on Docker](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-ApacheDS-on-Docker). 
![image](https://user-images.githubusercontent.com/15785031/70435927-b9c94200-1a4d-11ea-8498-62744ed1dcb9.png)


Please post further queries in [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che)
