### ISSUE TITLE
Error when executing mvn install

### ISSUE THREAD

**Issue by xxxyh** [dcm4che/dcm4che#591]
dcm4che version is 5.20.0 and requires the same version of DCM4CHE ImageIO OpenCV,there is only 5.19.1 DCM4CHE ImageIO OpenCV in maven repository

**Comment by gunterze** [comment]
Not reproduce-able. Check if you can access

https://raw.github.com/nroduit/mvn-repo/master/org/weasis/opencv/weasis-opencv-core/3.5.3/weasis-opencv-core-3.5.3.pom

from your build system-

**Comment by wangning08115** [comment]
yes, i can open this url. 
and my mirror url is : 
<url>http://repo2.maven.org/maven2/</url>

**Comment by gunterze** [comment]
Maven looks additionally in all repositories listed https://github.com/dcm4che/dcm4che/blob/master/pom.xml#L208-L222

**Comment by AbhiShubh** [comment]
I am also getting the same error  and the repository and dependency added in pom.xml are 👍 
`<repository>
            <id>www.dcm4che.org</id>
            <name>dcm4che Repository</name>
            <url>http://www.dcm4che.org/maven2</url>
</repository>

<dependency>
            <groupId>dcm4che</groupId>
            <artifactId>dcm4che-core</artifactId>
            <version>2.0.29</version>
  </dependency>
`
I am getting this error on mvn install 

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cyborg: Could not resolve dependencies for project com.mphrx:mphrx-cyborg:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at dcm4che:dcm4che-core:jar:2.0.29: Failed to read artifact descriptor for dcm4che:dcm4che-core:jar:2.0.29: Could not transfer artifact dcm4che:dcm4che:pom:2.0.29 from/to www.dcm4che.org (http://www.dcm4che.org/maven2): Transfer failed for http://www.dcm4che.org/maven2/dcm4che/dcm4che/2.0.29/dcm4che-2.0.29.pom: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by gunterze** [comment]
That's an issue tracker for dcm4che-5.x not for dcm4che-2.x.! Anyway the URL to the maven repository changed Feb 2018 to http**s**://www.dcm4che.org/maven2 or alternatively http://maven.dcm4che.org
