### ISSUE TITLE
Jpg2dcm: avc1 box not found

### ISSUE THREAD

**Issue by olegyuryev** [dcm4che/dcm4che#609]
**Describe the bug**
I can't convert a mp4 file to DICOM, an error occurs - "jpg2dcm: avc1 box not found".

**To Reproduce**
Open the cmd and write the command: jpg2dcm C:\Test\test.mp4 C:\Test\videoMP4.dcm

**Expected behavior**
I need to get DICOM file from mp4.

**Screenshots**
![Screen](https://user-images.githubusercontent.com/53606528/71668858-a1fa8a80-2d7b-11ea-8822-1d17eb666978.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Perhaps there are not enough codecs on my PC?
I will be glad to any help, thanks!

**Comment by hczedik** [comment]
Have you tried with other mp4 files already?

Can you share the mp4 file please?

**Comment by olegyuryev** [comment]
Yes, I tried to convert another file, another error occurs: "jpg2dcm: MPEG-4 AVC profile_idc/level_idc: 66/40 not supported"
![Screen2](https://user-images.githubusercontent.com/53606528/71670558-46330000-2d81-11ea-86c0-46b507e0a2cd.JPG)

Of course, here are 2 examples of videos that cause errors:
1. https://drive.google.com/open?id=1Uhk-kGFsPN6zi6Zc9uwcwv9HlESJbrUU
2. https://drive.google.com/open?id=1vTCp_A6uTW2DlnjtfaUpnG8W5eneF8Nj

**Comment by gunterze** [comment]
profile_idc/level_idc: 66/40 => H.264/MPEG-4 AVC Baseline Profile / Level 4 => is not one of the AVC Profile / Level combinations which can be encapsulated into a DICOM object according [DICOM PS 3.5](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/PS3.5.html), 8.2. Native or Encapsulated Format Encoding .

The MPEG-4 which conversion false with "avc1 box not found" is actually a H.264/MPEG-4 AVC Main Profile / Level 3 video, which also can't be encapsulated into a DICOM object according  DICOM PS 3.5. So all I can do is to make the failure message more descriptive.

**Comment by gunterze** [comment]
Was wrong: the sample which conversion fails with "avc1 box not found" is actually a H.264/MPEG-4 AVC High Profile / Level 4.1 video, and can therfore be encapsulated into a DICOM object.

The failure is caused by a limitation of the utility, to only look into the first track for the video stream - and in the sample the first track contains the audio stream.
