### ISSUE TITLE
dcm4che-tool-jpg2dcm: Optionally replace quicktime ('qt ') by ISO Base Media file ('isom') branch in File Type Box from Quicktime containers encapsulated in created DICOM instances

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#626]
```
Options:
...
    --qt2mp4             replace quicktime ('qt  ') by ISO Base Media file
                         ('isom') branch in Quicktime containers;
                         encapsulate Quicktime container verbatim by
                         default.

```
Related https://github.com/dcm4che/dcm4chee-arc-light/issues/2387

**Comment by vrindanayak** [comment]
This improvement is no longer needed, as one can directly use [ffmpeg tool](https://www.ffmpeg.org/) to convert a quicktime video file into a mp4 video file and then use [jpg2dcm tool](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-jpg2dcm/README.md) to convert the resulting mp4 file into a DICOM object.

**Comment by gunterze** [comment]
Replacing the brand name in the File Type Box is not sufficient, to convert a Quicktime to a valid MP4 container.
