### ISSUE TITLE
NativeJLSImageWriter and NativeJ2kImageWriter: consider passed value of Bits per Sample

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#637]
`org.dcm4che3.opencv.NativeJLSImageWriter` and `org.dcm4che3.opencv.NativeJ2kImageWriter` ignore passed value of Bits per Sample by 
```java
params[Imgcodecs.DICOM_PARAM_BITS_PER_SAMPLE] = desc.getBitsCompressed(); // Bits per sample
```
but always include all 16 bits into the compressed stream for images with Bits Allocated = 16.

From added TranscoderTests:
```java
    @Test
    public void testCompress12BitsJPLL() throws Exception {
        test("MR2_UNC", "MR2_UNC-JPLL.dcm", UID.JPEGLossless, true);
        assertEquals(12, jpegBitsPerSample("MR2_UNC-JPLL.dcm"));
    }

    @Test
    public void testCompress12BitsJLSL() throws Exception {
        test("MR2_UNC", "MR2_UNC-JLSL.dcm", UID.JPEGLSLossless, true);
        assertEquals(12, jpegBitsPerSample("MR2_UNC-JLSL.dcm"));
    }

    @Test
    public void testCompress12BitsJ2KR() throws Exception {
        test("MR2_UNC", "MR2_UNC-J2KR.dcm", UID.JPEG2000LosslessOnly, true);
        assertEquals(12, jpegBitsPerSample("MR2_UNC-J2KR.dcm"));
    }

```
last 2 fail with
```
java.lang.AssertionError: 
Expected :12
Actual   :16
```

**Comment by nroduit** [comment]
The JPEG-LS encoder handles 8/16-bit data.
The JPEG2000 encoder handles 8/16/32-bit data
So it should be OK to get 16-bit from the header.

The JPG encoders (with a specific 12-bit encoder):
1) 1.2.840.10008.1.2.4.50: Lossy compression with JPEG baseline => 8 bit
2) 1.2.840.10008.1.2.4.51: Lossy compression with JPEG extended sequential => 8/12 bit
3) 1.2.840.10008.1.2.4.53: Lossy compression with JPEG spectral selection => 8/12 bit
4) 1.2.840.10008.1.2.4.55: Lossy compression with JPEG full progression => 8/12 bit
5) 1.2.840.10008.1.2.4.57: Pseudo-Lossless JPEG compression => 8/12/16 bit
6) 1.2.840.10008.1.2.4.70: Lossless JPEG compression => 8/12/16 bit

**Comment by gunterze** [comment]
I was aware of the limitation of the JPEG Lossless codec, to only support 8/12/16 bit, but I thought CharLS and OpenJPEG supports  to pass any value between 8 and 16 for the number of bits per sample. Will comment out the tests and label the issue as improvement - guess the possible gain in compression rate will not justify to spent too much effort in it...

**Comment by nroduit** [comment]
Currently, it's not in the APIs but yes theoretically it is possible for JPEG200 and JPEG-LS. However, the benefit is not significant (at least for JPEG-LS).

I will see if it would be possible to add a parameter to force the number of bits and by default during transcoding keep the same number of bits.

**Comment by gunterze** [comment]
@nroduit s.o. #647
