### ISSUE TITLE
NativeJ2kImageWriter: signed pixel values are compressed as unsigned

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#647]
NativeJ2kImageWriter: signed pixel values are compressed as unsigned, which is a major issue for lossy compression. E.g.:

```
$ dcm2dcm -C maxPixelValueError=200 --j2ki ~/testdata/signedrangeimages/test16signed.dcm /tmp
Jan 27, 2020 10:24:57 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
22:24:57,706 DEBUG - Compressor: org.dcm4che3.opencv.NativeJ2kImageWriter
22:24:57,709 DEBUG - Verifier: org.dcm4che3.opencv.NativeImageReader
22:24:57,821 DEBUG - Compressed frame #1 in 82 ms, ratio 7.3845463:1
Jan 27, 2020 10:24:57 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
WARN: Force to use signed data as defined in DICOM
22:24:57,850 DEBUG - Verified compressed frame #1 in 28 ms - max pixel value error: 65535
Failed to transcode /home/gunter/testdata/signedrangeimages/test16signed.dcm: Decompressed pixel data differs up to 65535 from original pixel data
org.dcm4che3.imageio.codec.CompressionVerificationException: Decompressed pixel data differs up to 65535 from original pixel data
	at org.dcm4che3.imageio.codec.Transcoder.verify(Transcoder.java:864)
	at org.dcm4che3.imageio.codec.Transcoder.compressFrame(Transcoder.java:648)
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:492)
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:429)
	at org.dcm4che3.imageio.codec.Transcoder.access$300(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:387)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:366)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:411)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```

Seems the value passed by https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio-opencv/src/main/java/org/dcm4che3/opencv/NativeJ2kImageWriter.java#L124 is not considered by the encoder.

Added test
```java
public class TranscoderTest {
...
//    @Test - broken
    public void testSigned12BitsJ2KI() throws Exception {
        test("test16signed.dcm", "test16signed-J2KI.dcm", UID.JPEG2000, true);
        assertEquals(1, jpegPixelRepresentation("test16signed-J2KI.dcm"));
    }
```
fails with
```
[ERROR]   TranscoderTest.testSigned12BitsJ2KI:186 expected:<1> but was:<0>
```

**Comment by nroduit** [comment]
The jpeg2000 header is not consistent with dicom meta data. I will try to fix it in the next native lib update. This is an issue only if we separate the content (jp2) of the DICOM file.

JPEG-LS and JPEG expects that the input data are unsigned values but actually we also store signed data where negative values are treated  just as large positive values. The information on how to interpret the byte representation is not stored in the JPEG bit stream. The sign attribute is in DICOM.

**Comment by gunterze** [comment]
> The jpeg2000 header is not consistent with dicom meta data. I will try to fix it in the next native lib update. This is an issue only if we separate the content (jp2) of the DICOM file.

which is required by [DICOM PS 5.5](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_A.4.4)
> For all images, including all frames of a multi-frame image, the JPEG 2000 bit stream specified in [ISO/IEC 15444-1] shall be used. The optional JP2 file format header shall NOT be included.

----

> JPEG-LS and JPEG expects that the input data are unsigned values but actually we also store signed data where negative values are treated just as large positive values. The information on how to interpret the byte representation is not stored in the JPEG bit stream. The sign attribute is in DICOM.

Right. So it does not make sense to use JPEG-LS lossy (NEAR>0) for signed pixel data!

**Comment by nroduit** [comment]
Yes, JPEG-LS lossy should be not allowed due to the prediction algorithm based on the difference and with two's complement representation (where -1 (1111111111111111) will be considered far away from 0)

**Comment by nroduit** [comment]
I found the problem in the jpeg2000 encoder. The sign parameter was not read correctly.

Currently, as the values are stored unsigned with jpeg2000 encoder, there is the same problem as with jpeg-ls. However, I confirm that when storing signed values the jpeg2000 lossy compression works correctly (no artifact in the images). This fix will be available in the next version of the native library.

**Comment by gunterze** [comment]
Great. Thanks.
