### ISSUE TITLE
Feature request MLLP v2 -support

### ISSUE THREAD

**Issue by FinOxy** [dcm4che/dcm4che#655]
**Expected behavior**
dcm4che3.hl7.MLLPConnection.java (actually MLLPInputStream.java) does not support immediate ACK, NACK (MLLP v2 1.2.2.2 Commit Acknowledgement Block) response described at http://hl7.ihelse.net/hl7v3/infrastructure/transport/transport_mllp.html

**Comment by gunterze** [comment]
Add
```java
class MLLPConnection  implements Closeable {
...
    public MLLPConnection(Socket sock, MLLPRelease mllpRelease) throws IOException {...}
    public MLLPConnection(Socket sock, MLLPRelease mllpRelease, int bufferSize) throws IOException {...}
```
with
```java
public enum MLLPRelease {
    MLLP1,
    MLLP2
}
```
and `Connection.Protocol.HL7_MLLP2`:
```java
Connection conn = ...
conn.setProtocol(Connection.Protocol.HL7_MLLP2);
```
