### ISSUE TITLE
JPEG-LS lossy is not adapted to signed data

### ISSUE THREAD

**Issue by nroduit** [dcm4che/dcm4che#656]
JPEG-LS expects that the input data are unsigned values but actually we store signed data where negative values are treated just as large positive values. The information on how to interpret the byte representation is not stored in the JPEG bit stream. The sign attribute is in DICOM.

JPEG-LS lossy prediction algorithm is based on the difference in pixel values. This is an issue with two's complement representation of pixel data because for instance: the decimal value -1 ( binary is 1111111111111111) will be treated as a postive integer 65535 which is far away from 0.

The problem is magnified when the values use the full range of values.

Here is a result of near-lossless compression (error = 2) that show how far we are of near-lossless:
![Sélection_020](https://user-images.githubusercontent.com/993975/73518501-cb501a00-43fe-11ea-8b57-cff843998df8.png)

**Comment by gunterze** [comment]
https://groups.google.com/forum/#!topic/comp.protocols.dicom/QK2qb3CjGUo
