### ISSUE TITLE
Transcoder does not fully take ImageWriterFactory configuration into account

### ISSUE THREAD

**Issue by damienvdb06** [dcm4che/dcm4che#658]
The transcoder does not fully compress according to `ImageWriterFactory.properties`.
It uses the ImageWriterFactory to find the ImageWriter, but ends up using the `ImageWriter.getDefaultWriteParam()` instead of the transfer syntax's configured write param.

## Example

Default `ImageWriterFactory.properties` contains: 
```
1.2.840.10008.1.2.4.90:jpeg2000-cv:org.dcm4che3.opencv.NativeJ2kImageWriter::compressionType=LOSSLESS
```
Transcode some native dicom into JPEG2000Lossless:
```
  Transcoder transcoder = new Transcoder(inputStream);
  transcoder.setDestinationTransferSyntax(UID.JPEG2000LosslessOnly);
  transcoder.setIncludeFileMetaInformation(true);
  transcoder.transcode((t, dataset) -> outputStream);
```
### Expected output
Lossless compressed dicom

### Actual output 
Lossy compressed dicom

### Workaround
Force the compress params with the ImageWriterFactory's ones.
```
  Transcoder transcoder = new Transcoder(inputStream);
  transcoder.setDestinationTransferSyntax(destinationTransferSyntax);
  transcoder.setIncludeFileMetaInformation(true);
  try {
    ImageWriterFactory.ImageWriterParam writerParam = ImageWriterFactory.getImageWriterParam(destinationTransferSyntax);
    transcoder.setCompressParams(writerParam.getImageWriteParams());
  } catch (NullPointerException e) {
    // setCompressParams fails if your destination transfer syntax is not native since compressor
    // is not initialized.
  }
  transcoder.transcode((t, dataset) -> outputStream);

```

**Comment by gunterze** [comment]
Current version requires
```java
transcoder.setCompressParams(new Property[0]);
```
but no need to pass `ImageWriterFactory.getImageWriterParam(destinationTransferSyntax).
```
