### ISSUE TITLE
Unable to invoke neventReport as SCU

### ISSUE THREAD

**Issue by balazs-ge** [dcm4che/dcm4che#663]
We have a DICOM archive that claims it can send some notifications using the N-EVENT-REPORT protocol.
To be able to test it, I created a small SCU, that theoretically simulates the same workflow.
The problem is that when I run it, I get an "_org.dcm4che3.net.NoRoleSelectionException: No Role Selection for SOP Class <SOP Class UID> - ? as SCP negotiated_" when neventReport is called on a successfully open Association.

Looking into the source code I see that there is a pattern for each n-method which checks if the caller is an SCU, except for neventReport, which checks it is an SCP (_dcm4che-net/src/main/java/org/dcm4che3/net/Association.java_):

```
    public void neventReport(String asuid, String cuid, String iuid, int eventTypeId,
            Attributes data, String tsuid, DimseRSPHandler rspHandler)
            throws IOException, InterruptedException {
        PresentationContext pc = pcFor(asuid, tsuid);
        checkIsSCP(asuid);
        Attributes neventrq =
                Commands.mkNEventReportRQ(rspHandler.getMessageID(), cuid, iuid,
                        eventTypeId, data);
        invoke(pc, neventrq, DataWriterAdapter.forAttributes(data), rspHandler,
                conn.getSendTimeout(), conn.getResponseTimeout());
    }

```
Shouldn't the checkIsSCP(asuid) call actually be checkIsSCU(asuid), as for the other similar methods in the class? If not, how can I invoke an N-EVENT-REPORT-RQ without building it from low level?

Notes:
- The only example using the neventReport function I've found is in the dcm4che/dcm4chee-arc-light project, in the org.dcm4chee.arc.stgcmt.impl.StgCmtImpl class, but as I see, it's both SCU and SCP, thus the SCP condition is met, too.

- If I add as.getAAssociateAC().addRoleSelection(new RoleSelection(protocolSyntax, true, true)); before calling neventReport, the code runs, but I'm sure that this is definitely not the right solution.

**Comment by gunterze** [comment]
N-EVENT-REPORT RQs are sent from the SCP to the SCU. Therefore if  the SCP is initiating the Association, it has to negotiate the SCP role - without Role Negotiation, the Association Requestor is in SCU role!

Please post questions to https://groups.google.com/forum/#!forum/dcm4che
