### ISSUE TITLE
Association::checkException throws confusing exceptions

### ISSUE THREAD

**Issue by mbakhoff** [dcm4che/dcm4che#667]
Consider this code:
```
class MyConsoleApplication {
    static Association connect() {
        ApplicationEntity ae = ...; 
        Connection local, remote = ...; 
        AAssociateRQ rq = ...;
        return ae.connect(local, remote, rq);
    }
}
```

If something goes wrong, e.g. the called AE is wrong, then the method will crash and the following will get logged:

```
org.dcm4che3.net.pdu.AAssociateRJ: A-ASSOCIATE-RJ[result: 1 - rejected-permanent, source: 1 - service-user, reason: 7 - called-AE-title-not-recognized]]
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:182)
	at org.dcm4che3.net.Association$2.run(Association.java:521)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The issue is that the stacktrace contains no context or caller info, i.e. reference to `ae.connect(..)` in MyConsoleApplication. This is quite annoying when debugging various issues.

The cause of the partial stacktrace is here:
```
class org.dcm4che3.net.Association {
    private void checkException() throws IOException {
        if (ex != null)
            throw ex;
    }
}
```

The `checkException` method throws an exception that was captured in some random thread pool, without adding the caller context. 

Would it be possible to wrap the exception, so it would become `throw new IOException(ex);` (or something like that)? A similar approach is taken in java.util.concurrent.Future::get that wraps any propagated exceptions in ExecutionException. 

Affected version: dcm4che-net:5.16.2 (also present in the recent 5.20).

**Comment by gunterze** [comment]
Would brake the API: Existing clients may catch AAssociateRJ and AAbort to distinguish failure reasons.

**Comment by mbakhoff** [comment]
Thank you for into it
