### ISSUE TITLE
SAXWriter writes keyword PrivateCreatorID for private tags if corresponding dictionary is missing

### ISSUE THREAD

**Issue by dhohmeier** [dcm4che/dcm4che#672]
**Description of the bug**
SAXWriter writes keyword "PrivateCreatorID" for private tags eeee >= xx10 if corresponding dictionary is missing.

**To Reproduce**
Run the following test case:

    @Test
    public void testWriteAsXMLWithKeyword() throws Exception {
        Attributes attrs = new Attributes();
        attrs.setString("MYPRIVCREATOR", 0x77110001, VR.LO, "aaa");
        attrs.setString("MYPRIVCREATOR", 0x77110010, VR.LO, "bbb");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        SAXTransformerFactory tf = (SAXTransformerFactory) TransformerFactory.newInstance();
        TransformerHandler th = tf.newTransformerHandler();
        th.getTransformer().setOutputProperty(OutputKeys.INDENT, "yes");
        th.setResult(new StreamResult(out));
        SAXWriter saxWriter = new SAXWriter(th);
        saxWriter.setIncludeKeyword(true);
        saxWriter.setIncludeNamespaceDeclaration(true);
        saxWriter.write(attrs);
        String s = out.toString();
        Assert.assertFalse(s.contains("keyword=\"PrivateCreatorID\""));
    }

Tag (7711,xx01) does not have the keyword attribute as expected.
But for tag (7711,xx10), 'keyword="PrivateCreatorID"' is written to XML.

**Expected behavior**
The assertion should not fail. Because no corresponding private dictionary is available, both private tags should not have any keyword attribute.

**Analysis**
The following method in class SAXWriter sets the first two digits of private tags to zero and calls ElementDictionary for the keyword.

    private void addAttributes(int tag, VR vr, String privateCreator) {
        if (privateCreator != null)
            tag &= 0xffff00ff;
        if (includeKeyword) {
            String keyword = ElementDictionary.keywordOf(tag, privateCreator);
            if (keyword != null && !keyword.isEmpty())
                addAttribute("keyword", keyword);
        }
        addAttribute("tag", TagUtils.toHexString(tag));
        if (privateCreator != null)
            addAttribute("privateCreator", privateCreator);
        addAttribute("vr", vr.name());
    }

With no private dictionary, the call ends in the standard ElementDictionary and finally in the Keyword class which gives keyword "PrivateCreatorID" for the already modified tag if it matches also bit mask 0x000000F0:

    public static String valueOf(int tag) {
        if ((tag & 0x0000FFFF) == 0
                && (tag & 0xFFFD0000) != 0)
            return "GroupLength";
        if ((tag & 0x00010000) != 0)
            return ((tag & 0x0000FF00) == 0
                    && (tag & 0x000000F0) != 0)
                  ? "PrivateCreatorID"
                  : "";

**Possible Solution**
Assuming the private ElementDictionary takes care of the first two digits of the element id by applying tag & 0xFFFF00FF, the modification of private tag numbers could be done after the keyword attribute is written in the SAXWriter method:
 
    private void addAttributes(int tag, VR vr, String privateCreator) {
        if (includeKeyword) {
            String keyword = ElementDictionary.keywordOf(tag, privateCreator);
            if (keyword != null && !keyword.isEmpty())
                addAttribute("keyword", keyword);
        }
        if (privateCreator != null)
            tag &= 0xffff00ff;

**Comment by gunterze** [comment]
Thx!
