### ISSUE TITLE
Check for Compatible Specific Character Sets on merging two datasets

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#675]
Check for Compatible Specific Character Sets on merging two data sets, throwing an `IllegalArgumentException` if the check fails.

```java
    @Test(expected = IllegalArgumentException.class)
    public void testAddFromIncompatibleCharacterSet() throws Exception {
        Attributes a = new Attributes();
        a.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 100");
        a.setBytes(Tag.PatientName, VR.PN, "Äneas^Rüdiger".getBytes(StandardCharsets.ISO_8859_1));
        Attributes b = new Attributes();
        b.setNull(Tag.PatientName, VR.PN);
        b.addSelected(a, Tag.PatientName);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testAddIncompatibleCharacterSet() throws Exception {
        Attributes a = new Attributes();
        a.setNull(Tag.SpecificCharacterSet, VR.CS);
        Attributes b = new Attributes();
        b.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 100");
        b.setBytes(Tag.PatientName, VR.PN, "Äneas^Rüdiger".getBytes(StandardCharsets.ISO_8859_1));
        b.addAll(a);
    }
```

**Comment by hczedik** [comment]
Hi @gunterze,

unfortunately, this change is causing quite some pain (regression) for us.
To be honest, I regret a bit that I raised the performance concern (https://github.com/dcm4che/dcm4che/commit/c25e9f5ca9a17a56b399a0b523e4839d045d1fb6#r36878341) back then.

In particular:
Consider the following code like this, that we use a lot in our application:

```
Attributes a = new Attributes();
a.setSpecificCharacterSet("ISO_IR 192");
a.setString(Tag.PatientName, VR.LO, "Some^Nåme");

Attributes b = new Attributes();
b.setString(Tag.UnformattedTextValue, VR.LO, "Text üöä");

a.addAll(b);
```

Now, this works correctly, as expected, and does not throw an exception.
But, for other reasons, for certain customers, we want to change the default character set:

```
SpecificCharacterSet.setDefaultCharacterSet("ISO_IR 100");
```

And suddenly, with that set, the code above does fail with the exception.

I do understand why it fails and how we could correct it (e.g. by setting the same SpecificCharacterSet also on b), but it is quite a lot of changes throughout codebase, and it is hard to find all cases.

Now I was thinking, to solve this particular problem, we could maybe change the Attributes.containsNonASCIIStringValues method a bit:
within that method, change the `val != Value.NULL && vr.useSpecificCharacterSet()` check to something like this:
`val != Value.NULL && !(val instanceof String) && vr.useSpecificCharacterSet()`
(probably it should consider also String[] arrays)... with the reasoning that if the Strings are anyway already decoded (and no longer byte[] or bulkdata), then it is safe to copy those over.
Okay, I understand your concern, that it is not certain that the source characters can actually get encoded in the destination character set. But in this particular case the destination character set is UTF-8, which can represent all characters.

What do you think about that? I think it would alleviate our pain a bit.

Maybe additionally to that, we should even consider going back to the automatic conversion of character sets. At least in those cases where it can be considered safe.

For example, consider this code:

```
        Attributes attr = new Attributes();
        attr.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 192"); //$NON-NLS-1$
        attr.setBytes(Tag.UnformattedTextValue, VR.LO, "üöä".getBytes(StandardCharsets.UTF_8));

        Attributes other = new Attributes();
        other.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 100"); //$NON-NLS-1$
        other.setBytes(Tag.UnformattedTextValue, VR.LO, "äöü".getBytes(StandardCharsets.ISO_8859_1));

        attr.addSelected(other, Tag.UnformattedTextValue);
```

It fails, although in theory a safe conversion, in this case from latin1 to utf-8, would be possible. I know we could use Attributes.unifyCharacterSets(). But when only copying specific tags over that method is slow, as it converts all values. And additionally it potentially modifies the source and the destination Attributes, which is not always safe (or fails, if the Attributes is set to read-only.) So we would need to create copies first, which is even more inefficient.
An automatic conversion could be implemented more efficiently. In fact, I prefer the implementation as it was originally before I raised https://github.com/dcm4che/dcm4che/commit/c25e9f5ca9a17a56b399a0b523e4839d045d1fb6#r36878341

**Comment by gunterze** [comment]
Our experience with adding that check is in the opposite direction - it detected code issues, which would had harm us terrible in the long run. So I will not revert the check. I am open to implement some way to enable to deactivate the check by setting some static boolean flag or a system property.

**Comment by hczedik** [comment]
I don't want to completely disable it. I would rather suggest doing an automatic conversion in cases where it can be considered safe, see my two code examples above.

**Comment by gunterze** [comment]
> ```java
>Attributes attr = new Attributes();
>attr.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 192"); //$NON-NLS-1$
>attr.setBytes(Tag.UnformattedTextValue, VR.LO, "üöä".getBytes(StandardCharsets.UTF_8));
>
>Attributes other = new Attributes();
>other.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 100"); //$NON-NLS-1$
>other.setBytes(Tag.UnformattedTextValue, VR.LO, "äöü".getBytes(StandardCharsets.ISO_8859_1));
>
>attr.addSelected(other, Tag.UnformattedTextValue);
>```

**correctly** fails with:
`org.dcm4che3.data.IncompatibleSpecificCharacterSetException: Specific Character Sets [ISO_IR 192] and [ISO_IR 100] not compatible`

Otherwise you would get
```java
Attributes attr = new Attributes();
attr.setString(Tag.SpecificCharacterSet, VR.CS, "ISO_IR 192"); //$NON-NLS-1$
attr.setBytes(Tag.UnformattedTextValue, VR.LO, "äöü".getBytes(StandardCharsets.ISO_8859_1));

assertEquals("äöü", attr.getString(Tag.UnformattedTextValue));
```
```
org.junit.ComparisonFailure: 
Expected :äöü
Actual   :���
```

**Comment by hczedik** [comment]
Yes, i see, but in this case the addSelected method could do an automatic decoding, as it was done before the change in https://github.com/dcm4che/dcm4che/issues/651
