### ISSUE TITLE
DicomImageReader: Overlays only applied for monochrom PhotometricInterpretation

### ISSUE THREAD

**Issue by fwiller** [dcm4che/dcm4che#683]
The DicomImageReader has support for applying LUT and Overlay information.
But in case of e.g. RGB images the current implementation will neither apply LUT nor overlays.

see DicomImageReader.read():
````      
    if (pmi.isMonochrome()) {
            int[] overlayGroupOffsets = getActiveOverlayGroupOffsets(param);
            byte[][] overlayData = new byte[overlayGroupOffsets.length][];
            for (int i = 0; i < overlayGroupOffsets.length; i++) {
                overlayData[i] = extractOverlay(overlayGroupOffsets[i], raster);
            }
            cm = createColorModel(8, DataBuffer.TYPE_BYTE);
            SampleModel sm = createSampleModel(DataBuffer.TYPE_BYTE, false);
            raster = applyLUTs(raster, frameIndex, param, sm, 8);
            for (int i = 0; i < overlayGroupOffsets.length; i++) {
                applyOverlay(overlayGroupOffsets[i], 
                        raster, frameIndex, param, 8, overlayData[i]);
            }
    } else {
            cm = createColorModel(bitsStored, dataType);
    }
````
**Expected behavior**
LUT and Overlays should be applied

**Comment by gunterze** [comment]
Not aware that DICOM defines Modality and VOI LUT for color images.
Overlays can be applied - just did not yet met a DICOM RGB or COLOR PALETTE image making use of it..

**Comment by fwiller** [comment]
You are right with LUT! My fault to mention it.
I stumbled over some SecondaryCaptureImageStorage from Siemens with PhotometricInterpretation = RGB and Overlays which gets not rendered.
