### ISSUE TITLE
XML containing inline binary content followed by empty attribute is parsed incorrectly, with binary data being filled into the empty attribute

### ISSUE THREAD

**Issue by andpab** [dcm4che/dcm4che#698]
**Describe the bug**
When using the `ContentHandlerAdapter` to parse a valid NativeDicomModel XML string that contains a DicomAttribute of VR OB with an InlineBinary child node in Base64 encoding and a subsequent DicomAttribute with VR ST and no content, some binary content is being filled into the empty attribute.

**To Reproduce**

The following simplistic test reproduces the problem:

```
    @Test
    public void parseXmlContentWithInlineBinaryFollowedByEmptyDicomAttribute() throws ParserConfigurationException, SAXException, IOException {
        String inputXmlString =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<NativeDicomModel xml:space=\"preserve\">" +
            "  <DicomAttribute keyword=\"aaa\" tag=\"04070006\" privateCreator=\"MYPRIVCREATOR\" vr=\"OB\">\n" +
            "    <InlineBinary>" +
            "AAAAAAEHAQH/XAATQEBISFBISFBISFBISFBISFD/UgAMAAAAAQAFBAAAABZpaGRyAAACAAAAApgAAQcHAAAAAAAPY29scgEAAAAAABEAAAAAanAyY/9P/1EAKQAAAAACmAAAAg" +
            "AAAAAAAAAAAAAAApgAAAIAAAAAAAAAAAAMalAgIA0KhwoAAAAUZnR5cGpwMiAAAAAAanAyIAAAAC1qcDJoBAAB/2QADwABTFdGX0pQMl8yMDT/kAAKAAAAAAAUAAH/k4CAgICAgP/Z" +
            "    </InlineBinary>\n" +
            "  </DicomAttribute>\n" +
            "  <DicomAttribute keyword=\"bbb\" tag=\"04070007\" privateCreator=\"MYPRIVCREATOR\" vr=\"ST\"/>\n" +
            "</NativeDicomModel>";

        Attributes dataset = new Attributes();
        SAXParserFactory f = SAXParserFactory.newInstance();
        SAXParser parser = f.newSAXParser();
        ContentHandlerAdapter dcm4che3ContentHandlerAdapter = new ContentHandlerAdapter(dataset);
        parser.parse(new ByteArrayInputStream(inputXmlString.getBytes(StandardCharsets.UTF_8)), dcm4che3ContentHandlerAdapter);
        String emptyStAttributeContent= dataset.getString("MYPRIVCREATOR", 0x04070007);
        assertNull(emptyStAttributeContent);
    }
```

With dcm4che 5.22.0 the test fails as there is binary data in the supposedly empty second attribute.

**Expected behavior**
Attributes are parsed correctly and test succeeds. 

**Analysis**
It seems the flag `inlineBinary` in `ContentHandlerAdapter` is not set to false in some cases. Adding an `inlineBinary = false;` to the end of `endElement()` for example makes the test succeed.

**Comment by gunterze** [comment]
Exemplary bug report! Thx!

**Comment by hczedik** [comment]
This was a duplicate of the much older issue https://dcm4che.atlassian.net/browse/LIB-440 (which was moved to github as https://github.com/dcm4che/dcm4che/issues/52).
I have closed https://github.com/dcm4che/dcm4che/issues/52 and linked it to this one.
