### ISSUE TITLE
Unable to resolve dependency for dcm4che.

### ISSUE THREAD

**Issue by AbhiShubh** [dcm4che/dcm4che#718]
Hi all, I am also getting the same error and the repository and dependency added in pom.xml are 👍
`
www.dcm4che.org
dcm4che Repository
http://www.dcm4che.org/maven2
dcm4che dcm4che-core 2.0.29 ` I am getting this error on mvn install
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cyborg: Could not resolve dependencies for project com.mphrx:mphrx-cyborg:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at dcm4che:dcm4che-core:jar:2.0.29: Failed to read artifact descriptor for dcm4che:dcm4che-core:jar:2.0.29: Could not transfer artifact dcm4che:dcm4che:pom:2.0.29 from/to www.dcm4che.org (http://www.dcm4che.org/maven2): Transfer failed for http://www.dcm4che.org/maven2/dcm4che/dcm4che/2.0.29/dcm4che-2.0.29.pom: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by gunterze** [comment]
That's an issue tracker for dcm4che-5.x not for dcm4che-2.x.! Anyway the URL to the maven repository changed Feb 2018 to https://www.dcm4che.org/maven2 or alternatively http://maven.dcm4che.org
