### ISSUE TITLE
utility planarconfig may fail to detect correct Planar Configuration of US images

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#720]
Caused by the noisy characteristic of US images, the heuristic relying on (smaller) differences of sample values of adjoining pixels may fail.

- Use a different heuristic relying on predominance of gray over color pixels by default, but keep the option to use diff based heuristic for original color images - particular for visual light images.
- optionally restrict fixing of wrong values for attribute Planar Configuration for color-by-pixel **or** color-by-plane planar configuration

```
usage: planarconfig [--diff] [--uids] [--fix[0|1]] <file>|<directory>...
:
Options:
--diff   rely on (smaller) differences of sample values of adjoining pixels
         otherwise rely on predominance of gray over color pixels
--uids   log SOP Instance UIDs of files with not matching value of attribute
         Planar Configuration in file 'uids.log' in working directory.
--fix    fix all files with NOT matching value of attribute Planar Configuration
--fix0   fix value of attribute Planar Configuration with detected
         color-by-pixel planar configuration to 0
--fix1   fix value of attribute Planar Configuration with detected
         color-by-plane planar configuration to 1
```

**Comment by petrkalina** [comment]
using i.e.
[incorrectly-fixed-images.zip](https://github.com/dcm4che/dcm4che/files/4662289/incorrectly-fixed-images.zip)
