### ISSUE TITLE
Memory leak with the jpeg-lossless encoder

### ISSUE THREAD

**Issue by nroduit** [dcm4che/dcm4che#757]
See this [post](https://groups.google.com/d/msg/dcm4che/56YsaW5VsPA/eMIN9VMZBQAJ).

I can confirm that there is a memory leak using the tool jemalloc.

**Comment by nroduit** [comment]
Tested with jemalloc by converting a large dataset into jpeg-lossless:

[report-4.3.0-jpeglossless.pdf](https://github.com/dcm4che/dcm4che/files/4955701/report-4.3.0-jpeglossless.pdf)

[report-4.4.0-jpeglossless.pdf](https://github.com/dcm4che/dcm4che/files/4955702/report-4.4.0-jpeglossless.pdf)

**Comment by gunterze** [comment]
Fixed by #758
