### ISSUE TITLE
LIB-285  add pdf2dcm & dcm2pdf to dcm4che3-tool

### ISSUE THREAD

**Issue by hczedik** [dcm4che/dcm4che#76]
This issue was migrated from Jira.

Please check the original Jira issue for additional information and the actual Reporter:
http://dcm4che.org/jira/browse/LIB-285

**Comment by jssuttles** [comment]
👍

**Comment by hczedik** [comment]
Pull requests are welcome for this :-)

**Comment by vrindanayak** [comment]
Implemented by #297 and #490 
- [Pdf2Dcm](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-pdf2dcm/README.md)
- [Dcm2Pdf](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-dcm2pdf/README.md)
