### ISSUE TITLE
PaletteColorModel incorrectly inflate segmented Color LUTs

### ISSUE THREAD

**Issue by arturkanclerzCGM** [dcm4che/dcm4che#763]
**Describe the bug**
dcm4che in version 5 incorrectly interprets US 16bit Pallete Color study. It's seems like dcm4che treats this study like 8bit Pallette Color study. What interesting - dcm4che in version 2 handle this study correctly.

**To Reproduce**
1. Convert attachment's study via dcm2jpg from version 5 (jpg attached)
2. Convert attachment's study via dcm2jpg from version 2 (jpg attached)
3. Compare results

**Expected behavior**
dcm2jpg in version 5 should convert this study no worse than dcm2jpg in version 2

**Screenshots**
Correct result (from version 2):
![obraz](https://user-images.githubusercontent.com/68904605/88659332-296f6880-d0d5-11ea-8c4a-1e404f3a9654.png)

Incorrect result (from version 5):
![obraz](https://user-images.githubusercontent.com/68904605/88659455-5cb1f780-d0d5-11ea-9994-4d4fa7f3621d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version [dcm4che 5.22.3 dcm4che 2.0.29]

[dicom.zip](https://github.com/dcm4che/dcm4che/files/4988008/dicom.zip)

**Comment by gunterze** [comment]
Which version of dcm4che version 3 you used? Tried with 3.2.0 getting the same JPG as with current version 5.22.3.

**Comment by arturkanclerzCGM** [comment]
My mistake - it's was version 2.0.29.

So version 2.0.29 works fine

**Comment by arturkanclerzCGM** [comment]
When can i expect released version 5.22.4?

**Comment by gunterze** [comment]
in 1-2 weeks
