### ISSUE TITLE
In which table of a DCM4CHEE database can I find instance metadata to check if a instance support multiframe?

### ISSUE THREAD

**Issue by pablovegaimexhs** [dcm4che/dcm4che#764]
Hi everyone! I'm having problems doing a query for request if a instance has multi-frame. 

I can see a DCM4CHEE database scheme here: https://dcm4che.atlassian.net/wiki/spaces/ee2/pages/2555917/Database+Schema+Diagram?preview=/2555917/2557614/2.18.x%20Database%20Scheme.jpg

![image](https://user-images.githubusercontent.com/67170659/88816531-1e264680-d182-11ea-841f-d7ce7a90a001.png)

can you help with: In which table of a DCM4CHEE database can I find instance metadata to check if a instance support multiframe?

**Comment by gunterze** [comment]
As I remember right, dcm4chee-2 does not extract number of frames in a DB column. Better to ask at https://groups.google.com/forum/#!forum/dcm4che

**Comment by pablovegaimexhs** [comment]
Thanks a lot @gunterze !
