### ISSUE TITLE
Error during reading raster (java.io.EOFException)

### ISSUE THREAD

**Issue by arturkanclerzCGM** [dcm4che/dcm4che#770]
**Describe the bug**
In my repository I found a dicom file which is problematic for dcm4che. It's seems like dcm4che can't correctly interprets pixel data of this file during reading raster. 
After decompressing this dicom via gdcm, dcm4che correctly process this file.

**To Reproduce**
1. Convert attachment's study via dcm2jpg

**Expected behavior**
dcm4che should handle this study correctly.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/68904605/89642733-a4463980-d8b4-11ea-9a5a-187f7e8d262c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version dcm4che 5.22.3

Problematic study:
[sufinka.zip](https://github.com/dcm4che/dcm4che/files/5041167/sufinka.zip)

**Comment by gunterze** [comment]
The encode length and the VR of Pixel data is wrong: FFFFFFFFH and OB instead 57712 and OW!
Also the encode length of the data fragment is wrong:  57687 instead 57688.
See fixed file attached:
[sufinka.fixed.zip](https://github.com/dcm4che/dcm4che/files/5063990/sufinka.fixed.zip)
