### ISSUE TITLE
Getting EOF exception if 'Detached Study Management SOP Class (Retired)' is showing

### ISSUE THREAD

**Issue by hitesh7garg** [dcm4che/dcm4che#772]
**Describe the bug**
Getting EOF exception if 'Detached Study Management SOP Class (Retired)' is showing
I have one following observation. In case if dicom contains this tag
ReferencedStudySequence :
Item #0 xfffee000
ReferencedSOPClassUID : "1.2.840.10008.3.1.2.3.1" [ Detached Study Management SOP Class (Retired) ]
ReferencedSOPInstanceUID : "1.2.40.0.13.1.49050409869247541397420651861725016109"

Then those files are getting EOF exception
if it is like this : 
ReferencedPerformedProcedureStepSequence :
Item #0 xfffee000
InstanceCreationDate : "20080819"
InstanceCreationTime : "154251.000000"
InstanceCreatorUID : "1.3.46.670589.11.17521.5"
ReferencedSOPClassUID : "1.2.840.10008.3.1.2.3.3" [ Modality Performed Procedure Step SOP Class ]
ReferencedSOPInstanceUID : "1.3.46.670589.11.17521.5.0.5676.2008081915001418081"
InstanceNumber : "0"

Then it is successfully parsed.
**To Reproduce**
1. Try to parse a file using dcm4che-core toolkit present in maven.

**Expected behavior**
In my opinion it should be parsed as it is working fine with dicomParser.js library.

**Comment by gunterze** [comment]
Provide some sample file

**Comment by hitesh7garg** [comment]
https://drive.google.com/file/d/1iHnH_WT75zdbgFw7t4H5sE01L8o4_mEr/view?usp=sharing

**Comment by hitesh7garg** [comment]
Please download and check for all of these files present in this google drive link

**Comment by gunterze** [comment]
In all examples the encoded length of the pixel data exceeds the actual file length
