### ISSUE TITLE
mvn install error with timezones

### ISSUE THREAD

**Issue by fsleeman** [dcm4che/dcm4che#781]
From a fresh clone of the repo, running `mvn install` get to the test section and failed with this error:

INFO] Reactor Summary for dcm4che DICOM toolkit and utilities 5.22.5:
[INFO] 
[INFO] dcm4che DICOM toolkit and utilities ................ SUCCESS [  0.067 s]
[INFO] dcm4che-audit ...................................... SUCCESS [  1.652 s]
[INFO] dcm4che-dict ....................................... SUCCESS [  0.511 s]
[INFO] dcm4che-test-data .................................. SUCCESS [  0.010 s]
[INFO] dcm4che-core ....................................... FAILURE [  2.791 s]

...

[ERROR] Tests run: 48, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.019 s <<< FAILURE! - in org.dcm4che3.data.AttributesTest
[ERROR] testDateRangeSetTimezoneOffsetFromUTC(org.dcm4che3.data.AttributesTest)  Time elapsed: 0.005 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<19[]700101> but was:<19[691231-19]700101>
	at org.dcm4che3.data.AttributesTest.testDateRangeSetTimezoneOffsetFromUTC(AttributesTest.java:287)

[ERROR] testSetTimezoneOffsetFromUTC(org.dcm4che3.data.AttributesTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<19[70010]1> but was:<19[69123]1>
	at org.dcm4che3.data.AttributesTest.testSetTimezoneOffsetFromUTC(AttributesTest.java:270)

I am running Linux Mint 19.2 Cinnamon with JDK 1.8, is there a work around for this or can this test be skipped?

**Comment by gunterze** [comment]
Caused by #787
