### ISSUE TITLE
The libopencv_java.so (linux-x86) in binary tool doesn't work in Ubuntu ARM environment

### ISSUE THREAD

**Issue by welsleywu** [dcm4che/dcm4che#783]
When using the dcm2jpg tool, it shows the libopencv_java.so (linux-x86) does't not mathch current environment, but the environment is scripts auto detect. 
OS: Ubuntu ARM architecture

Following is the error details:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /root/ftimage/dcm4che/lib/linux-x86_64/libopencv_java.so: /root/ftimage/dcm4che/lib/linux-x86_64/libopencv_java.so:

**Comment by nroduit** [comment]
The next release will bring native libraries for ARM: linux-aarch64 and linux-armv7a

**Comment by welsleywu** [comment]
Thanks for your great help, the new arm SO file works fine, but it requires glibc2.27+. Is it possible also supporting lower version glibc2.17?

**Comment by nroduit** [comment]
Here are the dependencies of the linux build:
``` bash
$ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-aarch64.so 
GLIBC 2.17
GLIBC 2.27

$ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-armv7a.so 
GLIBC 2.4
GLIBC 2.6
GLIBC 2.7

$ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-s390x.so 
GLIBC 2.2
GLIBC 2.2.4
GLIBC 2.3
GLIBC 2.3.2
GLIBC 2.3.4
GLIBC 2.4
GLIBC 2.6
GLIBC 2.7

$ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-x86.so 
GLIBC 2.0
GLIBC 2.1
GLIBC 2.1.3
GLIBC 2.2
GLIBC 2.2.4
GLIBC 2.3
GLIBC 2.3.2
GLIBC 2.3.4
GLIBC 2.4
GLIBC 2.6
GLIBC 2.7
GLIBC 2.11

$ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-x86-64.so 
GLIBC 2.2.5
GLIBC 2.3
GLIBC 2.3.2
GLIBC 2.3.4
GLIBC 2.4
GLIBC 2.6
GLIBC 2.7
GLIBC 2.11
GLIBC 2.14
```

I use [dockross](https://github.com/dockcross/dockcross) for building but the previous image for aarch64 cannot build the project.

**Comment by welsleywu** [comment]
> Here are the dependencies of the linux build:
> 
> ```shell
> $ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-aarch64.so 
> GLIBC 2.17
> GLIBC 2.27
> 
> $ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-armv7a.so 
> GLIBC 2.4
> GLIBC 2.6
> GLIBC 2.7
> 
> $ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-s390x.so 
> GLIBC 2.2
> GLIBC 2.2.4
> GLIBC 2.3
> GLIBC 2.3.2
> GLIBC 2.3.4
> GLIBC 2.4
> GLIBC 2.6
> GLIBC 2.7
> 
> $ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-x86.so 
> GLIBC 2.0
> GLIBC 2.1
> GLIBC 2.1.3
> GLIBC 2.2
> GLIBC 2.2.4
> GLIBC 2.3
> GLIBC 2.3.2
> GLIBC 2.3.4
> GLIBC 2.4
> GLIBC 2.6
> GLIBC 2.7
> GLIBC 2.11
> 
> $ ./glibc-check.sh libopencv_java-4.5.0-dcm-linux-x86-64.so 
> GLIBC 2.2.5
> GLIBC 2.3
> GLIBC 2.3.2
> GLIBC 2.3.4
> GLIBC 2.4
> GLIBC 2.6
> GLIBC 2.7
> GLIBC 2.11
> GLIBC 2.14
> ```
> 
> I use [dockross](https://github.com/dockcross/dockcross) for building but the previous image for aarch64 cannot build the project.

Thanks for your time, we find the another machine to rebuild the GCLIB2.27, and get the so file, and it's easy to run on lower GCLIB version env.
