### ISSUE TITLE
No adapter implemented yet for FileCacheImageInputStream

### ISSUE THREAD

**Issue by dubacher** [dcm4che/dcm4che#785]
We use dcm4che (release 5.21.0) in our project to implement certain requirements in the realm of DICOM. Apart from this our backend handles many other requests which are not related to DICOM at all.

Since using dcm4che in our backend we encountered the issue that JPEG files could not be read anymore when reading them using javax.imageio.ImageIO. An IllegalArgumentException with the message "No adapter implemented yet for FileCacheImageInputStream" is thrown by StreamSegment.getStreamSegment.

The root cause of the issue is org.dcm4che3.opencv.NativeJPEGImageReaderSpi registered via IIORegistry (i.e. ServiceProvider). The SPI implementation is providing the org.dcm4che3.opencv.NativeImageReader even though it is not able to handle the FileCacheImageInputStream.

To fix the issue I currently manually unregister org.dcm4che3.opencv.NativeJPEGImageReaderSpi from the IIORegistry once the server is up-and-running.

I wonder what your thoughts are on this issue and how I could overcome this without having to apply the fix described above?

**Comment by gunterze** [comment]
You have to select the JDK Image Reader for JPEG yourself:
```java
Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("jpeg");
ImageReader reader = readers.next();
while (readers.hasNext()
   && !reader.getClass().getName().startsWith("com.sun.imageio.plugins")) {
            reader = readers.next();
}
```
