### ISSUE TITLE
Logo usage

### ISSUE THREAD

**Issue by peterneher** [dcm4che/dcm4che#793]
Hi dcm4chee Team,

is it allowed to use the dcm4chee logo in a scientific publication (JCO CCI) to indicate its usage? Is it the same license as the code?

Best,
Peter

**Comment by gunterze** [comment]
Yes, you may include https://www.dcm4che.org/images/dcm4che.gif in your paper.
Don't remember from where I took https://avatars0.githubusercontent.com/u/1788145?s=200&v=4 so I don't know if it's usage is legally correct.
