### ISSUE TITLE
How can i present chinese 

### ISSUE THREAD

**Issue by milktea-1** [dcm4che/dcm4che#812]
hello ,when i using  jpg2dcm this function ,my command is 
java -jar dcm4che-tool-jpg2dcm-5.21.0-jar-with-dependencies.jar jpg2dcm --no-app -m PatientName=周 -m PatientSex=M -- D:\test\3.jpg D:\test\
you can see i want to add  a chinese attribute ,but it dose not present chinese ,it present a "?"
![image](https://user-images.githubusercontent.com/40375885/98339810-4bb74180-2047-11eb-9e5a-961c1f8494e1.png)

**Comment by gunterze** [comment]
You have to also set [Specific Character Set](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_C.12.1.1.2) to a Code value for a Chinese Character set - typically `GB18030`

**Comment by milktea-1** [comment]
thank you
