### ISSUE TITLE
problem c-move on 5.11  dcm4chhe and radiant

### ISSUE THREAD

**Issue by prandl** [dcm4che/dcm4che#817]
good day Earlier I had an old version of the dcm4chee pax server. And everything worked perfectly. but after upgrading to version 5.11. stopped working with-move. the radiant program stopped working in C-move mode. Please help me enable this mode on the new version 5.11 running WILDFLY on synology. Passing C-move is necessary because many programs do not have the ability to change to C-get. THANKS

**Comment by gunterze** [comment]
Post questions to https://groups.google.com/u/1/g/dcm4che and describe your usage and problem in detail. "It stopped working", does not really help.
