### ISSUE TITLE
Problem with creating DICOMDIR using dcm4che version 5.22.6. Works in 5.22.5

### ISSUE THREAD

**Issue by CzibulaIstvan** [dcm4che/dcm4che#823]
Recently tried upgrading to dcm4che 5.22.6 and hit an issue when handling dicomdirs. I found that if I use version 5.22.5 the code work as expected (also wok in earlier versions of the library).
I construct a dicomdir in multiple separate steps: create the dicomdir, add some entries, close the DicomDirWriter, open again add some more entries and so on.
I manage to reduce my code to this sample code that reproduce the issue I have:

     public void test(File inst1, Attributes ds1, File inst2, Attributes ds2, File ddirF)
			throws IOException {
		RecordFactory recFact = new RecordFactory();
		DicomDirWriter.createEmptyDirectory(ddirF, UIDUtils.createUID(), null, null, null);
		try (DicomDirWriter out = DicomDirWriter.open(ddirF)) {
			addPatientStudySeriesInstances(inst1, ds1, out, recFact);
		}

		// reopen dicomdir
		try (DicomDirWriter out = DicomDirWriter.open(ddirF)) {
			addPatientStudySeriesInstances(inst2, ds2, out, recFact);
		}
               //try to read 
		try (DicomDirReader in = new DicomDirReader(ddirF)) {
			walk(in.findFirstRootDirectoryRecordInUse(true), in);
		}
	}

	private static void walk(Attributes rec, DicomDirReader in) throws IOException {
		while (rec != null) {
			walk(in.findLowerDirectoryRecordInUse(rec, true), in);
			rec = in.findNextDirectoryRecordInUse(rec, true);
		}
	}

	private static void addPatientStudySeriesInstances(File destF1, Attributes ds1, DicomDirWriter out,
			RecordFactory recFact) throws IOException {
		Attributes patRec = recFact.createRecord(RecordType.PATIENT, null, ds1, null, null);
		patRec = out.findOrAddPatientRecord(patRec);
		Attributes studyRec = recFact.createRecord(RecordType.STUDY, null, ds1, null, null);
		studyRec = out.findOrAddStudyRecord(patRec, studyRec);
		Attributes seriesRec = recFact.createRecord(RecordType.SERIES, null, ds1, null, null);
		seriesRec = out.findOrAddSeriesRecord(studyRec, seriesRec);
		Attributes instRec = recFact.createRecord(ds1, ds1.createFileMetaInformation(UID.ImplicitVRLittleEndian),
				out.toFileIDs(destF1));
		out.addLowerDirectoryRecord(seriesRec, instRec);
	}

Runing the code using dcm4che3 version 5.22.6 wil result in an exception:

`Exception in thread "main" org.dcm4che3.io.DicomStreamException: 0xFFFEE00D tag value too large, must be less than 2Gib
	at org.dcm4che3.io.DicomInputStream.tagValueTooLargeException(DicomInputStream.java:419)
	at org.dcm4che3.io.DicomInputStream.readHeader(DicomInputStream.java:448)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:526)
	at org.dcm4che3.io.DicomInputStream.readItem(DicomInputStream.java:764)
	at org.dcm4che3.media.DicomDirReader.readRecord(DicomDirReader.java:404)
	at org.dcm4che3.media.DicomDirReader.findRecordInUse(DicomDirReader.java:386)
	at org.dcm4che3.media.DicomDirReader.findLowerDirectoryRecord(DicomDirReader.java:241)
	at org.dcm4che3.media.DicomDirReader.findLowerDirectoryRecordInUse(DicomDirReader.java:235)`

if I execute the same code using dcm4che version 5.22.5 everything seams ok.
Is this a bug introduced in 5.22.6 or my code don't use the API correctly?  
I mention that if I add the 2 instance without closing and reopening than it's working in both versions.

**Comment by gunterze** [comment]
Bug already exists in versions before 5.22.6, but was not visible for _DicomDirReader_. Fixed by  #838
