### ISSUE TITLE
org.dcm4che3.mime.MultipartInputStream - wrong byte to int conversion on read()

### ISSUE THREAD

**Issue by navrkalpavel** [dcm4che/dcm4che#832]
The method org.dcm4che3.mime.MultipartInputStream.read() incorrectly handles byte to int conversion:
 ```

public int read() throws IOException {
        return isBoundary() ? -1 : buffer[rpos++];
}
```

The right conversion is:
```
public int read() throws IOException {
        return isBoundary() ? -1 : (buffer[rpos++] & 0xff);
}
```

See https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/io/ByteArrayInputStream.java#L144

Pavel Navrkal

**Comment by gunterze** [comment]
Thx!
