### ISSUE TITLE
Can i convert more than one jpg to one dcm?

### ISSUE THREAD

**Issue by milktea-1** [dcm4che/dcm4che#837]
hello, i wonder that Can i convert more than one jpg to one dcm?

**Comment by gunterze** [comment]
DICOM would permit to encapsulate multiple JPEG streams of equal dimension and color channel sampling into one DICOM Mutiframe object. But current version of dcm4che's jpg2dcm utility does not support such option.

Please post questions to https://groups.google.com/g/dcm4che
