### ISSUE TITLE
write Japanese with setDefaultCharacterSet to UTF8 (ISO_IR 192) fails with BufferOverflowException

### ISSUE THREAD

**Issue by wigun** [dcm4che/dcm4che#839]
**Describe the bug**
If you create a dataset with 'Value 1 of Attribute Specific Character Set (0008,0005) is Not Present' like '(0008,0005) \ISO 2022 IR 87' AND you have set the DefaultCharacterSet to UTF8, the writing of the dataset fails with a BufferOverflowException.

**To Reproduce**
Run this test:
```
    @Test
    void writeJapanese_setDefaultCharacterSet_Utf8() {
        String utf8 = "ISO_IR 192";
        SpecificCharacterSet.setDefaultCharacterSet(utf8);

        Attributes dataset = new Attributes();
        dataset.setString(Tag.SpecificCharacterSet, VR.CS, "", "ISO 2022 IR 87");
        dataset.setString(Tag.PatientName, VR.PN, "Yamada^Tarou=山田^太郎=やまだ^たろう");

        SpecificCharacterSet specificCharacterSet = dataset.getSpecificCharacterSet();
        //codec[0] is 'UTF_8', codec[1] is 'JIS_X_208' ?!?!?!

        VR.PN.toBytes(dataset.getValue(Tag.PatientName), specificCharacterSet);

        // this fails with a
        // java.nio.BufferOverflowException
        //	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:273)
        //	at org.dcm4che3.data.SpecificCharacterSet$Encoder.encode(SpecificCharacterSet.java:265)
        //	at org.dcm4che3.data.SpecificCharacterSet$ISO2022.encode(SpecificCharacterSet.java:309)

        // therefore any write dataset will fail as well
    }

```
**Expected behavior**
Writing of any datasets should succeed independent of the set DefaultCharacterSet by SpecificCharacterSet.setDefaultCharacterSet(String code)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - dcm4che 5.22.5

**Comment by wigun** [comment]
related or duplicate to https://github.com/dcm4che/dcm4che/issues/818 ?!

**Comment by gunterze** [comment]
related, but not duplicate.

**Comment by wigun** [comment]
This is a more simple test, which shows the issue, which I would expect to succeed:

```
    @Test
    public void testSetDefaultCharacterSetUtf8_valueOfJapanese() {
        SpecificCharacterSet.setDefaultCharacterSet("ISO_IR 192");
        SpecificCharacterSet specificCharacterSet = SpecificCharacterSet.valueOf("", "ISO 2022 IR 87");

        assertEquals("ISO_646", specificCharacterSet.codecs[0].name());
        assertEquals("JIS_X_208", specificCharacterSet.codecs[1].name());
    }
```

**Comment by gunterze** [comment]
Will fix it, by falling back to ASCII as default character set, if Specific Character Sets contains multiple code values and Default Character Set was set to "ISO_IR 192".

**Comment by wigun** [comment]
Only for Utf8 "ISO_IR 192" ? 
I would expect this to work for any changed Default Character Set.

**Comment by gunterze** [comment]
No, it should not happen setting a single byte character supplementing ASCII as Default Character Set
