### ISSUE TITLE
Javadoc failure for files created with XSLT in generated-sources directory

### ISSUE THREAD

**Issue by BradleyRoss** [dcm4che/dcm4che#84]
I was starting up with dcm4che again after a few years and was trying to create some Javadoc files.  When I tried running man javadoc:javadoc on the modules, I received a long list of errors.    I was using Javadoc 8 and many of the problems were due to the information in the javadoc comment related to the schema for the files in the generated-sources sections not having the greater than sign changed to &gt;.  I know that Javadoc 8 has a problem with this because it is much stricter on html syntax in the comments.  You are using group:javax.xml.bind artifact:jaxb-api version:2.1.  According tohttps://jaxb.java.net/2.2.5/docs/release-documentation.html, there was fix between 2.2.3u2 and 2.2.4 that may refer to this.  

There are some other Javadoc problems but they appear to be related to the source code.

This is what I received when I ran man javadoc:javadoc
[problems.txt](https://github.com/dcm4che/dcm4che/files/949308/problems.txt)

*** ***  ***   ***

I changed the versions for the following dependencies in dcm4che-audit/pom.xml and that seemed to have removed the problems with the illegal HTML in the Javadoc comments.

   <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.2.5</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <type>jar</type>
      <scope>test</scope>
    </dependency>

The resulting Javadocs can be found at https://bradleyross.github.io/dcm4che/apidocs

**Comment by hczedik** [comment]
Thank you @BradleyRoss !
`mvn javadoc:javadoc`
and
`mvn javadoc:aggregate`
should be working now.
