### ISSUE TITLE
Seeing i/o Exception when receiving and rejecting unexpected request

### ISSUE THREAD

**Issue by quintonn** [dcm4che/dcm4che#840]
**Describe the bug**
I have a project where I am noticing some exceptions being logged, but no indication if they are handled or dealt with anywhere, and our clients could potentially ask us.
In my specific case, I setup a dicom server with a specific set of transfer capabilities.
I exclude the TS **1.2.840.10008.1.2**.
I then make a request using the echoscu utility as follows:
`echoscu -d localhost 687`
The result in the command line seems correct and is what I would expect, that there are no acceptable presentation contexts:
```
$ echoscu -d localhost 687
D: $dcmtk: echoscu v3.6.5 2019-10-28 $
D:
D: Request Parameters:
D: ====================== BEGIN A-ASSOCIATE-RQ =====================
D: Our Implementation Class UID:      1.2.276.0.7230010.3.0.3.6.5
D: Our Implementation Version Name:   OFFIS_DCMTK_365
D: Their Implementation Class UID:
D: Their Implementation Version Name:
D: Application Context Name:    1.2.840.10008.3.1.1.1
D: Calling Application Name:    ECHOSCU
D: Called Application Name:     ANY-SCP
D: Responding Application Name: ANY-SCP
D: Our Max PDU Receive Size:    16384
D: Their Max PDU Receive Size:  0
D: Presentation Contexts:
D:   Context ID:        1 (Proposed)
D:     Abstract Syntax: =VerificationSOPClass
D:     Proposed SCP/SCU Role: Default
D:     Proposed Transfer Syntax(es):
D:       =LittleEndianImplicit
D: Requested Extended Negotiation: none
D: Accepted Extended Negotiation:  none
D: Requested User Identity Negotiation: none
D: User Identity Negotiation Response:  none
D: ======================= END A-ASSOCIATE-RQ ======================
I: Requesting Association
D: setting network send timeout to 60 seconds
D: setting network receive timeout to 60 seconds
D: Constructing Associate RQ PDU
D: PDU Type: Associate Accept, PDU Length: 171 + 6 bytes PDU header
D:   02  00  00  00  00  ab  00  01  00  00  41  4e  59  2d  53  43
D:   50  20  20  20  20  20  20  20  20  20  45  43  48  4f  53  43
D:   55  20  20  20  20  20  20  20  20  20  00  00  00  00  00  00
D:   00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
D:   00  00  00  00  00  00  00  00  00  00  10  00  00  15  31  2e
D:   32  2e  38  34  30  2e  31  30  30  30  38  2e  33  2e  31  2e
D:   31  2e  31  21  00  00  19  01  00  04  00  40  00  00  11  31
D:   2e  32  2e  38  34  30  2e  31  30  30  30  38  2e  31  2e  32
D:   50  00  00  2d  51  00  00  04  00  00  3f  fa  52  00  00  0f
D:   31  2e  32  2e  34  30  2e  30  2e  31  33  2e  31  2e  33  55
D:   00  00  0e  64  63  6d  34  63  68  65  2d  35  2e  32  32  2e
D:   34
D: Parsing an A-ASSOCIATE PDU
D: Association Parameters Negotiated:
D: ====================== BEGIN A-ASSOCIATE-AC =====================
D: Our Implementation Class UID:      1.2.276.0.7230010.3.0.3.6.5
D: Our Implementation Version Name:   OFFIS_DCMTK_365
D: Their Implementation Class UID:    1.2.40.0.13.1.3
D: Their Implementation Version Name: dcm4che-5.22.4
D: Application Context Name:    1.2.840.10008.3.1.1.1
D: Calling Application Name:    ECHOSCU
D: Called Application Name:     ANY-SCP
D: Responding Application Name: ANY-SCP
D: Our Max PDU Receive Size:    16384
D: Their Max PDU Receive Size:  16378
D: Presentation Contexts:
D:   Context ID:        1 (Transfer Syntaxes Not Supported)
D:     Abstract Syntax: =VerificationSOPClass
D:     Proposed SCP/SCU Role: Default
D:     Accepted SCP/SCU Role: Default
D: Requested Extended Negotiation: none
D: Accepted Extended Negotiation:  none
D: Requested User Identity Negotiation: none
D: User Identity Negotiation Response:  none
D: ======================= END A-ASSOCIATE-AC ======================
F: No Acceptable Presentation Contexts
```

But in my log file, I notice the following:
```
27 Nov 2020 11:24:52,350 [INFO ] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1) << A-ASSOCIATE-AC
27 Nov 2020 11:24:52,350 [DEBUG] {pool-6-thread-2} (org.dcm4che3.net.Association) A-ASSOCIATE-AC[
  calledAET: ANY-SCP
  callingAET: ECHOSCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.22.4
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 1/1
  PresentationContext[id: 1
    result: 4 - transfer-syntaxes-not-supported (provider rejection)
    ts: 1.2.840.10008.1.1 - Verification SOP Class
  ]
]
27 Nov 2020 11:24:52,350 [DEBUG] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): enter state: Sta6 - Association established and ready for data transfer
27 Nov 2020 11:24:52,350 [DEBUG] {pool-6-thread-2} (org.dcm4che3.net.Timeout) ANY-SCP<-ECHOSCU(1): start idle timeout of 300000ms
27 Nov 2020 11:24:52,365 [INFO ] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): i/o exception: java.net.SocketException: Connection reset in State: Sta6 - Association established and ready for data transfer
27 Nov 2020 11:24:52,365 [INFO ] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): close Socket[addr=/127.0.0.1,port=52027,localport=687]
27 Nov 2020 11:24:52,365 [DEBUG] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): enter state: Sta1 - Idle
27 Nov 2020 11:24:52,365 [DEBUG] {pool-6-thread-2} (org.dcm4che3.net.Timeout) ANY-SCP<-ECHOSCU(1): stop idle timeout
```

Specifically: **i/o exception: java.net.SocketException: Connection reset in State: Sta6 - Association established and ready for data transfer**

There is a SocketException because it was trying to write to the stream/channel/whatever it is called at this point.

I think I've found where this is happening in the codebase, in the [Association class](https://github.com/dcm4che/dcm4che/blob/441a7b4567254cece55904ab4a55c7417aa33839/dcm4che-net/src/main/java/org/dcm4che3/net/Association.java#L571).  
It makes a **negotiate** call and even if there were no valid presentation contexts, it continues to try and call write.  
My guess is that it should release or abort the connection at this point if there are no valid presentation contexts.   
I would provide a PR, but I'm not sure what should happen at this point, if anything, and what the chain is that got the code to this point.  

**To Reproduce**
1. Set up a dicom server with a specific set of supported Transfer Syntaxes, but **NOT** 1.2.840.10008.1.2  
2. Run the echoscu command: echoscu -d localhost 687
3. See the io exception message in the logs.

**Expected behavior**
There shouldn't be any exceptions logged

**Additional context**
This happens on Windows 10. I'm using the dch4che 5.22.4 libraries.
There is quite a bit of customization going on for my project, but i don't think it's causing or affecting the issues described here.

**Comment by quintonn** [comment]
Interestingly, if I try a c-echo request from a tool called Storage SCU Emulator, by dvtk, i don't see the mentioned issue.
Perhaps it is bug in the echoscu utility ??

**Comment by gunterze** [comment]
```
27 Nov 2020 11:24:52,365 [INFO ] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): i/o exception: java.net.SocketException: Connection reset in State: Sta6 - Association established and ready for data transfer
27 Nov 2020 11:24:52,365 [INFO ] {pool-6-thread-2} (org.dcm4che3.net.Association) ANY-SCP<-ECHOSCU(1): close Socket[addr=/127.0.0.1,port=52027,localport=687]
```
The SCU just drops the TCP connection.

The behavior of server side is correct, beside I am not sure if DICOM does not require an Association-acceptor to always provide the Verification SOP Class as SCP.

It should definitely **not** A-ABORT an association, if it does not provide any of the offered Presentation Contexts in the A-ASSOCIATE-RQ!

**Comment by quintonn** [comment]
But why does the dicom server end up in a state where it is expecting data transfer?   

Should it not prevent itself from getting to that point and closing the socket gracefully?

**Comment by gunterze** [comment]
The log you included shows a graceful closing of the socket!

**Comment by quintonn** [comment]
**i/o exception: java.net.SocketException: Connection reset in State: Sta6 - Association established and ready for data transfer**

This seems unclean though.
It was actually brought to our attention by a customer testing our product and was looking at logs for other reasons.

If I understood your first comment correct, it is because the calling system dropped the connection, is that right?
That would make sense why we have this socket exception.

But I'm wondering, since we know we have sent a rejection of some kind, maybe it should not enter state 6 and also try and close the socket from our side too. 
Not sure if it is possible to close the socket in a way so that neither client or server gets this SocketException though.

**Comment by gunterze** [comment]
Don't know what you mean with
> know we have sent a rejection of some kind

State 6 is entered after sending the A-ASSOCIATE-AC back to the remote DICOM peer.
On trying to read further PDU's from the socket, the i/o exception happens.
So for me the log describes what happened quite accurate.

**Comment by quintonn** [comment]
I mean we send "result: 4 - transfer-syntaxes-not-supported (provider rejection)"
As I mention, I am not too familiar with the lower level Dicom spec, but is the client supposed to send something back at this point, instead of just dropping the connection?
I mean, is it normal to keep trying to read from the socket even after sending a provider, or other, rejection?

**Comment by gunterze** [comment]
That's just the notification about the rejection of one offered Presentation Context in the A-ASSOCIATE-RQ.
It is **not** the rejection of the A-ASSOCIATE-RQ -  which communicated by returning an A-ASSOCIATE-RJ instead of the A-ASSOCIATE-AC PDU. So the Association is actual open, even if the only thing the client could do - because there was no offered Presentation Context accepted - is to release the Association gracefully.

**Comment by quintonn** [comment]
Ok, so if I understood, it's actually up to the client to end the connection better ??

That would explain why calling C-ECHO from the SCU emulator did not result in the socket exception, perhaps it handles this case better.

If this is the case, thanks for your time and effort to explain all of this.

**Comment by gunterze** [comment]
Right.

Anyway, I strongly recommend to always provide the Verification SOP Class as SCP by Association-acceptors, independently if that is required by DICOM - thought I read such requirement somewhere in some part, but I could not find it now - or not.

**Comment by quintonn** [comment]
How does the SCP provide the Verification SOP Class? 
You mean in the list of transfer capabilities?
I was just doing some tests on my pc, and didn't add that.
Our product will allow our users to configure the accepted UIDs and I assume they would add the Verification SOP class, since that's how they will probably test connectivity to other systems. 
But it's a good point, thanks.

**Comment by gunterze** [comment]
https://github.com/dcm4che/quickstart/blob/master/c-echo-scp/src/main/java/org/dcm4che3/quickstart/cechoscp/CEchoSCP.java#L75-L76

**Comment by quintonn** [comment]
Perfect, got it thanks.
