### ISSUE TITLE
Wrong storage-sop-classes.properties UID Renaming

### ISSUE THREAD

**Issue by NicolasLaheurte** [dcm4che/dcm4che#843]
In dcm4che-assembly/src/etc/dcmqrscp/storage-sop-classes.properties it seems the keyword "Retired" has been removed also when unnecessary.

Seen issues:
1. UltrasoundMultiFrameImageStorageRetired
UltrasoundMultiFrameImageStorage
Both renamed to:
UltrasoundMultiFrameImageStorage

2. UltrasoundImageStorageRetired
UltrasoundImageStorage
Both renamed to:
UltrasoundImageStorage

3. "NuclearMedicineImageStorageRetired" became "NuclearMedicineImageStorage" which isn't the same UID (both are existing).

No issue seen in query-sop-classes.properties / retrieve-sop-classes.properties but the same issue is found in sop-classes.properties.

**Comment by jssuttles** [comment]
Hey,
This fix wasn't quite right. 
NuclearMedicineImageStorage is different from NuclearMedicineImageStorageRetired.
1.2.840.10008.5.1.4.1.1.20
vs 
1.2.840.10008.5.1.4.1.1.5

**Comment by gunterze** [comment]
> Hey, This fix wasn't quite right. NuclearMedicineImageStorage is different from NuclearMedicineImageStorageRetired. 1.2.840.10008.5.1.4.1.1.20 vs 1.2.840.10008.5.1.4.1.1.5

Fixed files contain 
```
NuclearMedicineImageStorage:*
```
**and**
```
NuclearMedicineImageStorageRetired:*
```
!

**Comment by jssuttles** [comment]
Hi, sorry for bothering you again. 
But I just checked through https://github.com/dcm4che/dcm4che/blob/master/dcm4che-assembly/src/etc/storescp/sop-classes.properties again and it's not there.
It was removed in https://github.com/dcm4che/dcm4che/commit/ba4626dba2ff87c709f914e262124cb1cfe8990d#diff-777459a77c74a7f0837eb94f2a5a7141f4d8a8269affcb4dc2ef263e225b5eca.
Does this commit make sense?
![image](https://user-images.githubusercontent.com/8527741/137318446-f4676f4c-c29a-400d-8a4e-0b8e50c271c6.png)

**Comment by gunterze** [comment]
Also don't see the intention of https://github.com/dcm4che/dcm4che/commit/ba4626dba2ff87c709f914e262124cb1cfe8990d 
Will ask @nroduit .
