### ISSUE TITLE
Trying to write Attributes with bigEndian data to DicomOutputStream crashes

### ISSUE THREAD

**Issue by quintonn** [dcm4che/dcm4che#855]
If I create a DicomOutputStream object using the constructor that takes an OutputStream and transfer syntax value, and I provide **UID.ExplicitVRBigEndian** as the transfer syntax, when I call **writeDataset(fmi, dataset);** it throws an exception.  

And that exception seems hard-coded, so I assume it is there for a reason.  

I have a scenario where I parse an XML Dicom file to Attributes and then I need to convert it at a later stage to a byte array.  
If I attempt to use the DicomOutputStream with a ByteArrayOutputStream, and the transfer syntax is BigEndian, I am getting this error:  
``` Java
throw new IllegalStateException("explicitVR=" + explicitVR + ", bigEndian=" + bigEndian);
```

It seems to work if I check for BigEndian, and just set it to LittleEndian, but I would like to understand why this is happening and if this is indeed the desired behaviour, as I'm concerned the output images could be affected.  

1. Convert a BigEndian Dicom file to Attributes, using any method.  
2. Create a new DicomOutputStream with the constructor that takes an outputstream and tsuid as input and set the tsuid to UID.ExplicitVRBigEndian.  
3. Call writeDataSet(fmi, dataset) on the dicomoutputstream created.  

**Expected behavior**
Not to see any errors

**Comment by gunterze** [comment]
That behavior is intended:
File Meta Information must be always encoded with Explicit VR Little Endian.
DicomOutputStream.writeDataset(fmi, dataset) itself takes care to switch the Transfer Syntax which was specified by _(0002,0010) Transfer Syntax UID_ in the passed File Meta Information, before writing the Data set to the stream.
