### ISSUE TITLE
Warning about illegal reflective access

### ISSUE THREAD

**Issue by fordanic** [dcm4che/dcm4che#861]
**Describe the bug**
Warnings about illegal reflective access are printed during use of storescu.

**To Reproduce**
1. Use storescu to send DICOM objects to a DICOM SCP node.
2. Warnings about illegal reflective access are printed to the screen
INFO: Successfully loaded OpenCV native library.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dcm4che3.opencv.StreamSegment (file:/C:/binaries/dcm4che/lib/dcm4che-imageio-opencv-5.23.0.jar) to field javax.imageio.stream.FileImageInputStream.raf
WARNING: Please consider reporting this to the maintainers of org.dcm4che3.opencv.StreamSegment
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Expected behavior**
No warnings displayed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java: 
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment Corretto-15.0.1.9.1 (build 15.0.1+9)
OpenJDK 64-Bit Server VM Corretto-15.0.1.9.1 (build 15.0.1+9, mixed mode, sharing)
 - storescu: 5.23.0

**Comment by gunterze** [comment]
s. https://groups.google.com/g/dcm4che/c/p895tqjEz_8/m/0W3PKUYiBwAJ

**Comment by fordanic** [comment]
Thanks. Weird that I didn't find that thread when I was searching for it.
