### ISSUE TITLE
Unable to upload mp4 converted dcm image into xnat

### ISSUE THREAD

**Issue by KhyatiMehta3** [dcm4che/dcm4che#862]
Hello! 
I used jpg2dcm to convert an mp4 video to dicom. 
The conversion happens successfully, but unable to view the dicom appropriately using an online dcm viewer tool. 
I tried uploading the same on xnat and if fails there as well. 

I get this error when trying to upload it to xnat:
```
Extraction / Review summary:
Importing file (converted_dicom.dcm.zip)
Uploading to /data/xnat/cache/USERS/4/uploads/20210106_181755642/converted_dicom.dcm.zip ...
file uploaded
mkdir /data/xnat/prearchive/1/20210106_181755642
Importing to /data/xnat/prearchive/1/20210106_181755642
processing
looking for DICOM files
found 1 DICOM files
found DICOM study (2.25.235639961760135927127187981487464327323)
done finding DICOM
looking for ECAT files
found 0 ECAT files
done finding ECAT
done
Setting additional values for '_1'
failed to set appropriate field(s) for '_1'. Data may be publicly accessible until archived.
An error occurred adding the session to the prearchive database
```
can anyone help out here?

Thanks a lot!

**Comment by gunterze** [comment]
Guess the used viewer does not support to play MP4 videos. You may verify to send it  dcm4chee-arc, and play it in any browser accessing it by WADO URI.
