### ISSUE TITLE
Provide sample HL7v2.5.1 OMI^O23 message in dcm4che-assembly/src/etc/testdata/hl7/OMI^O23.hl7

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#871]
Provide sample HL7v2.5.1 OMI^O23 message in `dcm4che-assembly/src/etc/testdata/hl7/OMI^O23.hl7` demonstrating supported
 - [HL7 ADT to DICOM Mapping](https://dcm4chee-arc-hl7cs.readthedocs.io/en/latest/adt/inbound.html#adt-in-pid-dicom)
 - [HL7 Order to DICOM MWL Mapping](https://dcm4chee-arc-hl7cs.readthedocs.io/en/latest/orm/inbound.html#hl7-order-to-dicom-mwl-mapping)
 
 by default configuration, particularly including mapping of veterinary specified  DICOM Attributes:
 
Name | Tag
-- | --
Responsible Person | (0010, 2297)
Responsible Person Role | (0010, 2298)
Patient Species Description | (0010, 2201)
Patient Species Code Sequence | (0010, 2202)
|>Code Value | (0008, 0100)
|>Coding Scheme Designator | (0008, 0102)
|>Code Meaning | (0008, 0104)
Patient Breed Description | (0010, 2292)
Patient Breed Code Sequence | (0010, 2293)
|>Code Value | (0008, 0100)
|>Coding Scheme Designator | (0008, 0102)
|>Code Meaning | (0008, 0104)
Patient’s Sex Neutered | (0010, 2203)
Other Patient IDs Sequence | (0010, 1002)
|>Patient ID | (0010, 0020)
|>Issuer of Patient ID | (0010, 0021)
|>Type of Patient ID | (0010, 0022)

and 
Name | Tag
-- | --
Patient Weight | (0010, 1030)
Patient Size | (0010, 1020)
 
 Related https://github.com/dcm4che/dcm4chee-arc-light/issues/2965

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/1bbd3fa37f1f302b2f0d6684c7fcd6844bf75cd9
