### ISSUE TITLE
stowrs utility : Support "--accept" flag also for DICOM objects

### ISSUE THREAD

**Issue by madhub** [dcm4che/dcm4che#882]
**Describe the bug**
StowRS tool does not respect the user supplied "accept" header.
Example: 
`stowrs.bat --accept "application/dicom+json" --bearer <<auth_token>> --url <<stow-url>> <<dicom_file>> `

Command output
C:\dcm4che-5.23.0\bin>stowrs.bat **--accept "application/dicom+json"** --bearer "some-token" --url http://abc.com/studies C:\somedicomfile.dcm
10:48:01,618 INFO  - Storing objects.
10:48:01,727 INFO  - > POST http://abc.com/studies
10:48:01,727 INFO  - > Content-Type: multipart/related; type="application/dicom"; boundary=myboundary
10:48:01,728 INFO  - > **Accept: application/dicom+xml**
10:48:01,728 INFO  - > Authorization: Bearer some-token

**To Reproduce**
Run stowrs.bat with proper url & dicom file & accept heade
`C:\dcm4che-5.23.0\bin>stowrs.bat **--accept "application/dicom+json"** --bearer "some-token" --url http://abc.com/studies C:\somedicomfile.dcm`

**Expected behavior**
Should use the user supplied accept header which is **application/dicom+json** instead of default **Accept: application/dicom+xml**

**Screenshots**
![image](https://user-images.githubusercontent.com/8907962/106093832-080c3980-6157-11eb-9800-a95be47fc409.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809

**Additional context**
Change required in `StowRS.setContentAndAcceptType` function
https://github.com/dcm4che/dcm4che/blob/985635d5548816323c49dcb30a624854e9c3f202/dcm4che-tool/dcm4che-tool-stowrs/src/main/java/org/dcm4che3/tool/stowrs/StowRS.java#L408

**Comment by vrindanayak** [comment]
@madhub : As you may see in the stowrs tool's help page, the allowed options for `--accept` flag are `xml` or `json`, which the tool then translates to `application/dicom+xml` or `application/dicom+json` - allowing the user to type less :). Also the help page mentions that for DICOM objects, `application/dicom+xml` will be used by default, implying the `--accept` flag is ignored even if specified. I no longer remember the motivation to keep this default behavior of `Accept` header for DICOM objects as this tool was refactored as part of dcm4che/dcm4chee-arc-light#651 issue.

Nevertheless, I have updated the tool to keep this consistent similar to bulkdata uploads. 

![Screenshot_20210128_100257](https://user-images.githubusercontent.com/15785031/106114704-291d5c00-6150-11eb-88e5-5e23c0027d06.png)
