### ISSUE TITLE
DCM compression problem

### ISSUE THREAD

**Issue by advanceMaster** [dcm4che/dcm4che#885]
I encapsulated a DCM compression service, let this service run, the service memory consumption will be higher and higher, and will not be released
![image](https://user-images.githubusercontent.com/51150412/106544798-1daca500-6543-11eb-839f-8283f44b8af7.png)
dcm4che-5.16.1 jdk1.8.0_121  win10-64

**Comment by nroduit** [comment]
Could be related to this [issue](https://github.com/dcm4che/dcm4che/issues/757) which has been fixed.
