### ISSUE TITLE
Creator-less Private Tag cause equals() to throw Null Pointer Exception

### ISSUE THREAD

**Issue by komaldeeps96** [dcm4che/dcm4che#900]
**Describe the bug**
Private Tags with no PrivateCreator causes Null Pointer Exception.

**To Reproduce**
Add the following test to AttributesTest and it fails 
```
@Test
    public void testPrivateTagEquals() {
    	Attributes a1 = new Attributes();
    	a1.setString(0x55330010, VR.LO, "Visus Change");
        a1.setString(0x55331134, VR.LO, "MRI");
        
        Attributes a2 = new Attributes();
        a2.setString(0x55330010, VR.LO, "Visus Change");
        a2.setString(0x55331134, VR.LO, "MRI");
        
        assertTrue(a1.equals(a2));
        assertTrue(a2.equals(a1));
    }
```

**Expected behavior**
Should not throw a NPE.

**Proposed Change**
There should be a null check before calling privateCreator.equals method.
```
if (privateCreator!=null && privateCreator.equals(creatorID))
                    return creatorTag;
```

**Comment by alan-farquhar** [comment]
It is worth noting that this was discovered when we were ingesting a dicom object with only a private tag and this class was throwing a null pointer exception.
