### ISSUE TITLE
dcm4che-conf-core-api jar contains extra classes

### ISSUE THREAD

**Issue by wtellis** [dcm4che/dcm4che#91]
The dcm4che-conf-core-api-3.3.8.jar  in Maven contains classes for the Apache Commons BeanUtils and Logging library. This can cause problems if an application is using different versions of these libraries.

**Comment by BradleyRoss** [comment]
Actually, there are a number of cases where this type of problem occurs.  For example, the references to the slf4j and log4j artifacts.  The best way to handle these is probably to place of the dependencies for these jars in dcm4che-parent and give them a scope of provided.  Projects that have a dependency on the dcm4che artifacts will then be expected to provide their own versions of the code.  Putting the dependencies in the dcm4che-parent artifact will then make it easier to keep track of things.  I have been going through a lot of the pom.xml files and will provide more details when I finish my analysis.  Another item is that my current version of the pom.xml files appears to be using 2.2-beta-5 of maven-assembly-plugin where I tried to specify version 2.6 or 2.3.  There is also something strange about the maven-site-info-reports-plugin artifact.

If you look at the output to sysout and syserr streams, there appear to be a number of warning messages.

Look at https://bradleyaross.wordpress.com/2016/07/11/javadocs-and-maven/ and https://bradleyaross.wordpress.com/2016/05/05/java-logging-frameworks/ for more of my notes on the subject.  You might also want to consider a gh-pages branch for dcm4che/dcm4che that would be viewable at http://dcm4che.github.io/dcm4che .

Bradley A. Ross
e-mail bradleyross@me.com
http://www.linkedin.com/in/bradleyross2 <http://www.linkedin.com/in/bradleyross2> 
blog http://bradleyaross.wordpress.com <http://bradleyaross.wordpress.com/> 
Git http://bradleyross.github.io/tutorials <http://bradleyross.github.io/tutorials>

**Comment by BradleyRoss** [comment]
Is it possible that the artifact maven-site-info-reports-plugin in pom.xml for dcm4che-parent should be maven-project-info-reports-plugin.  As I said I'm going through the Maven log line by line and this might explain some of the warnings.  It is saying that it can't find a version number for maven-project-info-reports-plugin and there is no link for project-site-info-reports-plugin on the Project Plugin Management page.

**Comment by hczedik** [comment]
@wtellis Thanks for reporting. The issue with the apache classes in dcm4che-conf-core-api.jar is fixed.

@BradleyRoss If you find additional problems, please open new issues, instead of commenting into this one.
