### ISSUE TITLE
testSetTimezoneOffsetFromUTC() fails if system timezone has negativ UTC time offset

### ISSUE THREAD

**Issue by brentkellohen** [dcm4che/dcm4che#928]
**Describe the bug**
mvn install fails after fresh pull of code and install of Maven 3.6.3 on Manjaro ArchLinux

```
[INFO] Running org.dcm4che3.data.AttributesTest
[ERROR] Tests run: 49, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.017 s <<< FAILURE! - in org.dcm4che3.data.AttributesTest
[ERROR] testSetTimezoneOffsetFromUTC(org.dcm4che3.data.AttributesTest)  Time elapsed: 0.005 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<19[70010]1> but was:<19[69123]1>
        at org.dcm4che3.data.AttributesTest.testSetTimezoneOffsetFromUTC(AttributesTest.java:292)
```

**To Reproduce**
1. Pull dcm4che commit 127af6e
2. Install maven 3.6.3
3. Run mvn install in dcm4che directory

**Expected behavior**
Build successful

**Screenshots**
![image](https://user-images.githubusercontent.com/17730896/112063989-836ae580-8b1f-11eb-91b4-b75b8a844d98.png)

**Desktop (please complete the following information):**
See above

**Additional context**
I did have a version of DCMTK installed and was unsure if this may have conflicted with the installation. This was uninstalled but the error persists. 

Java version
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```

**Comment by gunterze** [comment]
What's the system timezone?
```
$ timedatectl
               Local time: Di 2021-03-23 07:55:07 CET
           Universal time: Di 2021-03-23 06:55:07 UTC
                 RTC time: Di 2021-03-23 06:55:07    
                Time zone: Europe/Vienna (CET, +0100)
System clock synchronized: yes                       
              NTP service: active                    
          RTC in local TZ: no   
```

**Comment by brentkellohen** [comment]
![image](https://user-images.githubusercontent.com/17730896/112171078-caed8200-8bb0-11eb-8567-0bba3cfb20e5.png)

**Comment by gunterze** [comment]
Related to #787.

Comment out
```java
    /*
        @Test
        public void testSetTimezoneOffsetFromUTC() throws Exception {

```
