### ISSUE TITLE
Export and Import Dicm Files

### ISSUE THREAD

**Issue by mbx2015** [dcm4che/dcm4che#93]
How can I export dicom files from my client machine to the pacs server, and how to download dicom files from pacs server to local machine ??

**Comment by Hesham-Elbadawi** [comment]
Please use the google group.

**Comment by hczedik** [comment]
Google Group: https://groups.google.com/forum/#!forum/dcm4che

**Comment by mbx2015** [comment]
I Already posted in the group,
Thanks
