### ISSUE TITLE
findscu: Unable to recover non-ASCII text from DICOM attributes

### ISSUE THREAD

**Issue by jap1968** [dcm4che/dcm4che#95]
findscu: Unable to recover non-ASCII text from DICOM attributes

Our PACS stores information in several fields encoded as ISO-8859-1 (latin-1). So far, we were able to recover properly this information using dcmqr (from dcm4che2 toolset) but right now we are unable to recover these fields using findscu (from dcm4che3 toolset).

You can find the description of our problem in the last two messages of this (rather old) thread:
http://forums.dcm4che.org/jiveforums/thread.jspa?messageID=18779
Notice that we were able to solve the problem back in 2011 using dcmqr, but we pretend to use the new findscu software in a new project.

Our storage server does not store information about specific character set (the attribute (0008,0005) is empty), so, maybe our PACS server is not perfectly configured. Would it be possible to recover the proper strings using findscu?

Examples:

dcmqr:
```
$ LANG=es_ES.iso-8859-1 /usr/local/dcm4che/dcm4che2/bin/dcmqr DCMTEST@127.0.0.1:104 -q 00100020='80701'|iconv -f ISO-8859-1 -t UTF8 | grep '(0008,1030)'

(0008,1030) LO #6 [tórax] Study Description
(0008,1030) LO #6 [tórax] Study Description

```
Perfect!!!

findscu:
```
$ LANG=es_ES.iso-8859-1 /usr/local/dcm4che/dcm4che3/bin/findscu -b DCMQR -c DCMTEST@127.0.0.1:104 -m 00100020='80701' -m 00080005='ISO-8859-1' | grep '(0008,1030)'

(0008,1030) LO [t�rax] StudyDescription
(0008,1030) LO [t�rax] StudyDescription
```

I have tried with different locales, as well as using different values for the SpecificCharacterSet attribute, but so far we have been unable to recover correctly any fields containing non-ASCII characters.

**Comment by gunterze** [comment]
It's a problem of your server! You may patch findscu changing the default character set from ASCII to  ISO-8859-1 by calling SpecificCharacterSet.setDefaultCharacterSet("ISO_IR 100") before performing the query. Please post further question in the [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che).
