### ISSUE TITLE
www.dcm4che.org site down

### ISSUE THREAD

**Issue by ebremer** [dcm4che/dcm4che#975]
https://www.dcm4che.org/ appears to be down right now.

**Comment by gunterze** [comment]
Not for me:
```
$ curl -v https://www.dcm4che.org/
*   Trying 195.201.27.249:443...
* Connected to www.dcm4che.org (195.201.27.249) port 443 (#0)
```

**Comment by ebremer** [comment]
Strange:
![image](https://user-images.githubusercontent.com/4094961/123103895-6e467100-d404-11eb-932d-21dc569d0290.png)

**Comment by ebremer** [comment]
It appears to be strictly a DNS issue as I could connect using your direct ip address.

**Comment by ebremer** [comment]
Google and Cloudflare failed. "Alternate DNS" succeeded.
![image](https://user-images.githubusercontent.com/4094961/123104671-2411bf80-d405-11eb-971a-ec792c15c866.png)

**Comment by ebremer** [comment]
"alternate DNS" down too.  The ip returned is for their web server to say it failed.

**Comment by nnl-1** [comment]
cannot build my project on https://bitbucket.org/ due to this issue also.

**Comment by gunterze** [comment]
We opened a ticket at our domain provider...

**Comment by ebremer** [comment]
I did that for myself until the DNS is fixed.  FYI - on Windows, the hosts file is:
c:\Windows\System32\Drivers\etc\hosts

**Comment by Homersbm** [comment]
> I did that for myself until the DNS is fixed. FYI - on Windows, the hosts file is:
> c:\Windows\System32\Drivers\etc\hosts

How did you make it work?
I kept "195.201.27.249  www.dcm4che.org" in  c:\Windows\System32\Drivers\etc\hosts file but i see error 
"DNS error (the host name of the page you are looking for does not exist)"

**Comment by ebremer** [comment]
There are many potential reasons for this.  Take a look at the answer to this question:

https://serverfault.com/questions/452268/hosts-file-ignored-how-to-troubleshoot

**Comment by Homersbm** [comment]
Is this repository:https://maven.scijava.org/content/repositories/public/ reliable?

**Comment by maltempi** [comment]
for the ones are building DCM4CHE on docker image, I'm doing this trick based on gunterze's workaround:

`docker build . --add-host=maven.dcm4che.org:195.201.27.249`

**Comment by gunterze** [comment]
DNS is fixed:
```
$ dig @8.8.8.8 www.dcm4che.org

; <<>> DiG 9.16.8-Ubuntu <<>> @8.8.8.8 www.dcm4che.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13844
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.dcm4che.org.		IN	A

;; ANSWER SECTION:
www.dcm4che.org.	14311	IN	A	195.201.27.249

;; Query time: 28 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fr Jul 02 09:40:28 CEST 2021
;; MSG SIZE  rcvd: 60
```

**Comment by Homersbm** [comment]
Try Accessing the Dependencies like this.. It works..
<dependency>
			<groupId>com.github.dcm4che.dcm4che</groupId>
			<artifactId>dcm4che-core</artifactId>
			<version>5.23.1</version>
</dependency>

**Comment by gunterze** [comment]
outage is resolved

**Comment by liad-signalpet** [comment]
This seems to happen again? my builds are failing.
