### ISSUE TITLE
Continuous integration using Travis CI

### ISSUE THREAD

**Issue by hczedik** [dcm4che/dcm4che#99]
Enable automatic continuous builds and tests using travis-ci.org

Builds will be available on: https://travis-ci.org/dcm4che/dcm4che

**Comment by hczedik** [comment]
Builds available on: https://travis-ci.org/dcm4che/dcm4che

**Comment by hczedik** [comment]
No longer available due to #160.

**Comment by gunterze** [comment]
Now also available for new master
